-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Infeasi_Res_S2_projPos22_Pipeline_projPos is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    primalInfeasRay_SVfifo_ub_i_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    primalInfeasRay_SVfifo_ub_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasRay_SVfifo_ub_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasRay_SVfifo_ub_i_empty_n : IN STD_LOGIC;
    primalInfeasRay_SVfifo_ub_i_read : OUT STD_LOGIC;
    primalInfeasBound_fifo_ub_i_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    primalInfeasBound_fifo_ub_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasBound_fifo_ub_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasBound_fifo_ub_i_full_n : IN STD_LOGIC;
    primalInfeasBound_fifo_ub_i_write : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Infeasi_Res_S2_projPos22_Pipeline_projPos is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110100";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv32_F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110011";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_133 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110011";
    constant ap_const_lv32_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110100";
    constant ap_const_lv32_17E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111110";
    constant ap_const_lv32_173 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110011";
    constant ap_const_lv32_1B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110100";
    constant ap_const_lv32_1BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111110";
    constant ap_const_lv32_1B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110011";
    constant ap_const_lv32_1F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110100";
    constant ap_const_lv32_1FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111110";
    constant ap_const_lv32_1F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln393_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal primalInfeasRay_SVfifo_ub_i_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal primalInfeasBound_fifo_ub_i_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln395_fu_237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_reg_824 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_reg_824_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_7_reg_830 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_7_reg_830_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_8_reg_836 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_8_reg_836_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_9_reg_842 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_9_reg_842_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_s_reg_848 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_s_reg_848_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_1_reg_854 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_1_reg_854_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_2_reg_860 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_2_reg_860_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_3_reg_866 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln395_3_reg_866_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln401_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_reg_872 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_reg_872_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_1_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_1_reg_877 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_1_reg_877_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_2_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_2_reg_882 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_2_reg_882_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_3_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_3_reg_887 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_3_reg_887_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_4_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_4_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_4_reg_892_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_5_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_5_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_5_reg_897_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_6_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_6_reg_902 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_6_reg_902_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_7_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_7_reg_907 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_7_reg_907_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_8_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_8_reg_912 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_8_reg_912_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_9_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_9_reg_917 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_9_reg_917_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_10_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_10_reg_922 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_10_reg_922_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_11_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_11_reg_927 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_11_reg_927_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_12_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_12_reg_932 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_12_reg_932_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_13_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_13_reg_937 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_13_reg_937_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_14_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_14_reg_942 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_14_reg_942_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_15_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_15_reg_947 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln401_15_reg_947_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_962 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_967 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_972 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_977 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_982 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_124 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln393_fu_217_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (30 downto 0);
    signal primalInfeasRay_SVfifo_ub_i_read_local : STD_LOGIC;
    signal or_ln404_i_fu_785_p9 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal primalInfeasBound_fifo_ub_i_write_local : STD_LOGIC;
    signal tmp_1_fu_147_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_152_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_fu_157_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_fu_162_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_167_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_10_fu_172_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_fu_177_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_14_fu_182_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_fu_207_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_311_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_fu_321_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_2_fu_337_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_1_fu_347_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_4_fu_369_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_2_fu_379_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_6_fu_401_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_3_fu_411_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_8_fu_433_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_4_fu_443_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_s_fu_465_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_5_fu_475_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_11_fu_497_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_6_fu_507_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_13_fu_529_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln401_7_fu_539_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal or_ln401_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_1_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_2_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_3_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_4_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_5_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_6_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln401_7_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_1_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_2_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_3_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_4_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_5_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_6_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln401_7_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln404_7_fu_778_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_6_fu_771_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_5_fu_764_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_4_fu_757_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_3_fu_750_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_2_fu_743_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_1_fu_736_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln404_fu_729_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dcmp_64ns_64ns_1_1_no_dsp_1_U478 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_1_fu_147_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_1_fu_147_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U479 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_3_fu_152_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_3_fu_152_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U480 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_5_fu_157_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_5_fu_157_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U481 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_7_fu_162_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_7_fu_162_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U482 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_9_fu_167_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_9_fu_167_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U483 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_10_fu_172_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_10_fu_172_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U484 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_12_fu_177_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_12_fu_177_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U485 : component Infeasi_Res_S2_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_14_fu_182_p0,
        din1 => ap_const_lv64_0,
        opcode => ap_const_lv5_4,
        dout => tmp_14_fu_182_p2);

    flow_control_loop_pipe_sequential_init_U : component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln393_fu_211_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_124 <= add_ln393_fu_217_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_124 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln401_10_reg_922 <= icmp_ln401_10_fu_485_p2;
                icmp_ln401_11_reg_927 <= icmp_ln401_11_fu_491_p2;
                icmp_ln401_12_reg_932 <= icmp_ln401_12_fu_517_p2;
                icmp_ln401_13_reg_937 <= icmp_ln401_13_fu_523_p2;
                icmp_ln401_14_reg_942 <= icmp_ln401_14_fu_549_p2;
                icmp_ln401_15_reg_947 <= icmp_ln401_15_fu_555_p2;
                icmp_ln401_1_reg_877 <= icmp_ln401_1_fu_331_p2;
                icmp_ln401_2_reg_882 <= icmp_ln401_2_fu_357_p2;
                icmp_ln401_3_reg_887 <= icmp_ln401_3_fu_363_p2;
                icmp_ln401_4_reg_892 <= icmp_ln401_4_fu_389_p2;
                icmp_ln401_5_reg_897 <= icmp_ln401_5_fu_395_p2;
                icmp_ln401_6_reg_902 <= icmp_ln401_6_fu_421_p2;
                icmp_ln401_7_reg_907 <= icmp_ln401_7_fu_427_p2;
                icmp_ln401_8_reg_912 <= icmp_ln401_8_fu_453_p2;
                icmp_ln401_9_reg_917 <= icmp_ln401_9_fu_459_p2;
                icmp_ln401_reg_872 <= icmp_ln401_fu_325_p2;
                trunc_ln395_1_reg_854 <= primalInfeasRay_SVfifo_ub_i_dout(383 downto 320);
                trunc_ln395_2_reg_860 <= primalInfeasRay_SVfifo_ub_i_dout(447 downto 384);
                trunc_ln395_3_reg_866 <= primalInfeasRay_SVfifo_ub_i_dout(511 downto 448);
                trunc_ln395_7_reg_830 <= primalInfeasRay_SVfifo_ub_i_dout(127 downto 64);
                trunc_ln395_8_reg_836 <= primalInfeasRay_SVfifo_ub_i_dout(191 downto 128);
                trunc_ln395_9_reg_842 <= primalInfeasRay_SVfifo_ub_i_dout(255 downto 192);
                trunc_ln395_reg_824 <= trunc_ln395_fu_237_p1;
                trunc_ln395_s_reg_848 <= primalInfeasRay_SVfifo_ub_i_dout(319 downto 256);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln401_10_reg_922_pp0_iter2_reg <= icmp_ln401_10_reg_922;
                icmp_ln401_11_reg_927_pp0_iter2_reg <= icmp_ln401_11_reg_927;
                icmp_ln401_12_reg_932_pp0_iter2_reg <= icmp_ln401_12_reg_932;
                icmp_ln401_13_reg_937_pp0_iter2_reg <= icmp_ln401_13_reg_937;
                icmp_ln401_14_reg_942_pp0_iter2_reg <= icmp_ln401_14_reg_942;
                icmp_ln401_15_reg_947_pp0_iter2_reg <= icmp_ln401_15_reg_947;
                icmp_ln401_1_reg_877_pp0_iter2_reg <= icmp_ln401_1_reg_877;
                icmp_ln401_2_reg_882_pp0_iter2_reg <= icmp_ln401_2_reg_882;
                icmp_ln401_3_reg_887_pp0_iter2_reg <= icmp_ln401_3_reg_887;
                icmp_ln401_4_reg_892_pp0_iter2_reg <= icmp_ln401_4_reg_892;
                icmp_ln401_5_reg_897_pp0_iter2_reg <= icmp_ln401_5_reg_897;
                icmp_ln401_6_reg_902_pp0_iter2_reg <= icmp_ln401_6_reg_902;
                icmp_ln401_7_reg_907_pp0_iter2_reg <= icmp_ln401_7_reg_907;
                icmp_ln401_8_reg_912_pp0_iter2_reg <= icmp_ln401_8_reg_912;
                icmp_ln401_9_reg_917_pp0_iter2_reg <= icmp_ln401_9_reg_917;
                icmp_ln401_reg_872_pp0_iter2_reg <= icmp_ln401_reg_872;
                tmp_10_reg_977 <= tmp_10_fu_172_p2;
                tmp_12_reg_982 <= tmp_12_fu_177_p2;
                tmp_14_reg_987 <= tmp_14_fu_182_p2;
                tmp_1_reg_952 <= tmp_1_fu_147_p2;
                tmp_3_reg_957 <= tmp_3_fu_152_p2;
                tmp_5_reg_962 <= tmp_5_fu_157_p2;
                tmp_7_reg_967 <= tmp_7_fu_162_p2;
                tmp_9_reg_972 <= tmp_9_fu_167_p2;
                trunc_ln395_1_reg_854_pp0_iter2_reg <= trunc_ln395_1_reg_854;
                trunc_ln395_2_reg_860_pp0_iter2_reg <= trunc_ln395_2_reg_860;
                trunc_ln395_3_reg_866_pp0_iter2_reg <= trunc_ln395_3_reg_866;
                trunc_ln395_7_reg_830_pp0_iter2_reg <= trunc_ln395_7_reg_830;
                trunc_ln395_8_reg_836_pp0_iter2_reg <= trunc_ln395_8_reg_836;
                trunc_ln395_9_reg_842_pp0_iter2_reg <= trunc_ln395_9_reg_842;
                trunc_ln395_reg_824_pp0_iter2_reg <= trunc_ln395_reg_824;
                trunc_ln395_s_reg_848_pp0_iter2_reg <= trunc_ln395_s_reg_848;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln393_fu_217_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv31_1));
    and_ln401_1_fu_670_p2 <= (tmp_3_reg_957 and or_ln401_1_fu_666_p2);
    and_ln401_2_fu_679_p2 <= (tmp_5_reg_962 and or_ln401_2_fu_675_p2);
    and_ln401_3_fu_688_p2 <= (tmp_7_reg_967 and or_ln401_3_fu_684_p2);
    and_ln401_4_fu_697_p2 <= (tmp_9_reg_972 and or_ln401_4_fu_693_p2);
    and_ln401_5_fu_706_p2 <= (tmp_10_reg_977 and or_ln401_5_fu_702_p2);
    and_ln401_6_fu_715_p2 <= (tmp_12_reg_982 and or_ln401_6_fu_711_p2);
    and_ln401_7_fu_724_p2 <= (tmp_14_reg_987 and or_ln401_7_fu_720_p2);
    and_ln401_fu_661_p2 <= (tmp_1_reg_952 and or_ln401_fu_657_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_00001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_00001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(primalInfeasRay_SVfifo_ub_i_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (primalInfeasRay_SVfifo_ub_i_empty_n = ap_const_logic_0);
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(primalInfeasBound_fifo_ub_i_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (primalInfeasBound_fifo_ub_i_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln393_fu_211_p2)
    begin
        if (((icmp_ln393_fu_211_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_124, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_124;
        end if; 
    end process;

    i_cast_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),32));
    icmp_ln393_fu_211_p2 <= "1" when (signed(i_cast_fu_207_p1) < signed(p_read)) else "0";
    icmp_ln401_10_fu_485_p2 <= "0" when (tmp_s_fu_465_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_11_fu_491_p2 <= "1" when (trunc_ln401_5_fu_475_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_12_fu_517_p2 <= "0" when (tmp_11_fu_497_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_13_fu_523_p2 <= "1" when (trunc_ln401_6_fu_507_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_14_fu_549_p2 <= "0" when (tmp_13_fu_529_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_15_fu_555_p2 <= "1" when (trunc_ln401_7_fu_539_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_1_fu_331_p2 <= "1" when (trunc_ln401_fu_321_p1 = ap_const_lv52_0) else "0";
    icmp_ln401_2_fu_357_p2 <= "0" when (tmp_2_fu_337_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_3_fu_363_p2 <= "1" when (trunc_ln401_1_fu_347_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_4_fu_389_p2 <= "0" when (tmp_4_fu_369_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_5_fu_395_p2 <= "1" when (trunc_ln401_2_fu_379_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_6_fu_421_p2 <= "0" when (tmp_6_fu_401_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_7_fu_427_p2 <= "1" when (trunc_ln401_3_fu_411_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_8_fu_453_p2 <= "0" when (tmp_8_fu_433_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln401_9_fu_459_p2 <= "1" when (trunc_ln401_4_fu_443_p4 = ap_const_lv52_0) else "0";
    icmp_ln401_fu_325_p2 <= "0" when (tmp_fu_311_p4 = ap_const_lv11_7FF) else "1";
    or_ln401_1_fu_666_p2 <= (icmp_ln401_3_reg_887_pp0_iter2_reg or icmp_ln401_2_reg_882_pp0_iter2_reg);
    or_ln401_2_fu_675_p2 <= (icmp_ln401_5_reg_897_pp0_iter2_reg or icmp_ln401_4_reg_892_pp0_iter2_reg);
    or_ln401_3_fu_684_p2 <= (icmp_ln401_7_reg_907_pp0_iter2_reg or icmp_ln401_6_reg_902_pp0_iter2_reg);
    or_ln401_4_fu_693_p2 <= (icmp_ln401_9_reg_917_pp0_iter2_reg or icmp_ln401_8_reg_912_pp0_iter2_reg);
    or_ln401_5_fu_702_p2 <= (icmp_ln401_11_reg_927_pp0_iter2_reg or icmp_ln401_10_reg_922_pp0_iter2_reg);
    or_ln401_6_fu_711_p2 <= (icmp_ln401_13_reg_937_pp0_iter2_reg or icmp_ln401_12_reg_932_pp0_iter2_reg);
    or_ln401_7_fu_720_p2 <= (icmp_ln401_15_reg_947_pp0_iter2_reg or icmp_ln401_14_reg_942_pp0_iter2_reg);
    or_ln401_fu_657_p2 <= (icmp_ln401_reg_872_pp0_iter2_reg or icmp_ln401_1_reg_877_pp0_iter2_reg);
    or_ln404_i_fu_785_p9 <= (((((((select_ln404_7_fu_778_p3 & select_ln404_6_fu_771_p3) & select_ln404_5_fu_764_p3) & select_ln404_4_fu_757_p3) & select_ln404_3_fu_750_p3) & select_ln404_2_fu_743_p3) & select_ln404_1_fu_736_p3) & select_ln404_fu_729_p3);

    primalInfeasBound_fifo_ub_i_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, primalInfeasBound_fifo_ub_i_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            primalInfeasBound_fifo_ub_i_blk_n <= primalInfeasBound_fifo_ub_i_full_n;
        else 
            primalInfeasBound_fifo_ub_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    primalInfeasBound_fifo_ub_i_din <= or_ln404_i_fu_785_p9;
    primalInfeasBound_fifo_ub_i_write <= primalInfeasBound_fifo_ub_i_write_local;

    primalInfeasBound_fifo_ub_i_write_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            primalInfeasBound_fifo_ub_i_write_local <= ap_const_logic_1;
        else 
            primalInfeasBound_fifo_ub_i_write_local <= ap_const_logic_0;
        end if; 
    end process;


    primalInfeasRay_SVfifo_ub_i_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, primalInfeasRay_SVfifo_ub_i_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            primalInfeasRay_SVfifo_ub_i_blk_n <= primalInfeasRay_SVfifo_ub_i_empty_n;
        else 
            primalInfeasRay_SVfifo_ub_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    primalInfeasRay_SVfifo_ub_i_read <= primalInfeasRay_SVfifo_ub_i_read_local;

    primalInfeasRay_SVfifo_ub_i_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            primalInfeasRay_SVfifo_ub_i_read_local <= ap_const_logic_1;
        else 
            primalInfeasRay_SVfifo_ub_i_read_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln404_1_fu_736_p3 <= 
        ap_const_lv64_0 when (and_ln401_1_fu_670_p2(0) = '1') else 
        trunc_ln395_7_reg_830_pp0_iter2_reg;
    select_ln404_2_fu_743_p3 <= 
        ap_const_lv64_0 when (and_ln401_2_fu_679_p2(0) = '1') else 
        trunc_ln395_8_reg_836_pp0_iter2_reg;
    select_ln404_3_fu_750_p3 <= 
        ap_const_lv64_0 when (and_ln401_3_fu_688_p2(0) = '1') else 
        trunc_ln395_9_reg_842_pp0_iter2_reg;
    select_ln404_4_fu_757_p3 <= 
        ap_const_lv64_0 when (and_ln401_4_fu_697_p2(0) = '1') else 
        trunc_ln395_s_reg_848_pp0_iter2_reg;
    select_ln404_5_fu_764_p3 <= 
        ap_const_lv64_0 when (and_ln401_5_fu_706_p2(0) = '1') else 
        trunc_ln395_1_reg_854_pp0_iter2_reg;
    select_ln404_6_fu_771_p3 <= 
        ap_const_lv64_0 when (and_ln401_6_fu_715_p2(0) = '1') else 
        trunc_ln395_2_reg_860_pp0_iter2_reg;
    select_ln404_7_fu_778_p3 <= 
        ap_const_lv64_0 when (and_ln401_7_fu_724_p2(0) = '1') else 
        trunc_ln395_3_reg_866_pp0_iter2_reg;
    select_ln404_fu_729_p3 <= 
        ap_const_lv64_0 when (and_ln401_fu_661_p2(0) = '1') else 
        trunc_ln395_reg_824_pp0_iter2_reg;
    tmp_10_fu_172_p0 <= trunc_ln395_1_reg_854;
    tmp_11_fu_497_p4 <= primalInfeasRay_SVfifo_ub_i_dout(446 downto 436);
    tmp_12_fu_177_p0 <= trunc_ln395_2_reg_860;
    tmp_13_fu_529_p4 <= primalInfeasRay_SVfifo_ub_i_dout(510 downto 500);
    tmp_14_fu_182_p0 <= trunc_ln395_3_reg_866;
    tmp_1_fu_147_p0 <= trunc_ln395_reg_824;
    tmp_2_fu_337_p4 <= primalInfeasRay_SVfifo_ub_i_dout(126 downto 116);
    tmp_3_fu_152_p0 <= trunc_ln395_7_reg_830;
    tmp_4_fu_369_p4 <= primalInfeasRay_SVfifo_ub_i_dout(190 downto 180);
    tmp_5_fu_157_p0 <= trunc_ln395_8_reg_836;
    tmp_6_fu_401_p4 <= primalInfeasRay_SVfifo_ub_i_dout(254 downto 244);
    tmp_7_fu_162_p0 <= trunc_ln395_9_reg_842;
    tmp_8_fu_433_p4 <= primalInfeasRay_SVfifo_ub_i_dout(318 downto 308);
    tmp_9_fu_167_p0 <= trunc_ln395_s_reg_848;
    tmp_fu_311_p4 <= primalInfeasRay_SVfifo_ub_i_dout(62 downto 52);
    tmp_s_fu_465_p4 <= primalInfeasRay_SVfifo_ub_i_dout(382 downto 372);
    trunc_ln395_fu_237_p1 <= primalInfeasRay_SVfifo_ub_i_dout(64 - 1 downto 0);
    trunc_ln401_1_fu_347_p4 <= primalInfeasRay_SVfifo_ub_i_dout(115 downto 64);
    trunc_ln401_2_fu_379_p4 <= primalInfeasRay_SVfifo_ub_i_dout(179 downto 128);
    trunc_ln401_3_fu_411_p4 <= primalInfeasRay_SVfifo_ub_i_dout(243 downto 192);
    trunc_ln401_4_fu_443_p4 <= primalInfeasRay_SVfifo_ub_i_dout(307 downto 256);
    trunc_ln401_5_fu_475_p4 <= primalInfeasRay_SVfifo_ub_i_dout(371 downto 320);
    trunc_ln401_6_fu_507_p4 <= primalInfeasRay_SVfifo_ub_i_dout(435 downto 384);
    trunc_ln401_7_fu_539_p4 <= primalInfeasRay_SVfifo_ub_i_dout(499 downto 448);
    trunc_ln401_fu_321_p1 <= primalInfeasRay_SVfifo_ub_i_dout(52 - 1 downto 0);
end behav;
