-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Infeasi_Res_S2_ediv_7_Pipeline_ediv is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    primalInfeasBound_edotfifo_lb_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    primalInfeasBound_edotfifo_lb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasBound_edotfifo_lb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    primalInfeasBound_edotfifo_lb_empty_n : IN STD_LOGIC;
    primalInfeasBound_edotfifo_lb_read : OUT STD_LOGIC;
    colScale_fifo_lb_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    colScale_fifo_lb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colScale_fifo_lb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colScale_fifo_lb_empty_n : IN STD_LOGIC;
    colScale_fifo_lb_read : OUT STD_LOGIC;
    temp_lb_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    temp_lb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    temp_lb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    temp_lb_full_n : IN STD_LOGIC;
    temp_lb_write : OUT STD_LOGIC;
    n_6 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Infeasi_Res_S2_ediv_7_Pipeline_ediv is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter37 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter38 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter39 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter40 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter41 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter42 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter43 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter44 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter45 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter46 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter47 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter48 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter49 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter50 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter51 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter52 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter53 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter54 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter55 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter56 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter57 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter58 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter59 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state60_pp0_stage0_iter59 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln416_fu_159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal primalInfeasBound_edotfifo_lb_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal colScale_fifo_lb_blk_n : STD_LOGIC;
    signal temp_lb_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln418_fu_179_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_reg_528 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_1_reg_533 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_2_reg_538 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_3_reg_543 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_4_reg_548 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_5_reg_553 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_6_reg_558 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln418_7_reg_563 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_fu_255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_reg_568 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_1_reg_573 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_2_reg_578 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_3_reg_583 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_4_reg_588 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_5_reg_593 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_6_reg_598 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln419_7_reg_603 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln416_fu_149_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (30 downto 0);
    signal primalInfeasBound_edotfifo_lb_read_local : STD_LOGIC;
    signal colScale_fifo_lb_read_local : STD_LOGIC;
    signal or_ln426_s_fu_489_p9 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal temp_lb_write_local : STD_LOGIC;
    signal grp_fu_97_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_97_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_101_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_101_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln413_fu_155_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_97_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_101_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_7_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_6_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_5_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_4_fu_473_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_3_fu_469_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_2_fu_465_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_1_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln426_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter35_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter36_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter37_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter38_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter39_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter40_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter41_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter42_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter43_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter44_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter45_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter46_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter47_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter48_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter49_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter50_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter51_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter52_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter53_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter54_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter55_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter56_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter57_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter58_reg : STD_LOGIC;
    signal ap_done_int_frp : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal frp_pipeline_valid_U_valid_out : STD_LOGIC_VECTOR (59 downto 0);
    signal frp_pipeline_valid_U_num_valid_datasets : STD_LOGIC_VECTOR (6 downto 0);
    signal pf_temp_lb_U_data_out : STD_LOGIC_VECTOR (511 downto 0);
    signal pf_temp_lb_U_data_out_vld : STD_LOGIC;
    signal pf_temp_lb_U_pf_ready : STD_LOGIC;
    signal pf_temp_lb_U_pf_done : STD_LOGIC;
    signal ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83 : STD_LOGIC;
    signal ap_frp_data_req_primalInfeasBound_edotfifo_lb : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_next_issued_colScale_fifo_lb : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_issued_nxt_colScale_fifo_lb_op93 : STD_LOGIC;
    signal ap_frp_data_req_colScale_fifo_lb : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal ap_frp_data_req_colScale_fifo_lb_op93 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_frp_roi_pvb_no_fwd_prs : BOOLEAN;
    signal ap_condition_frp_pvb_no_bkwd_prs : BOOLEAN;
    signal ap_condition_frp_pvb_pf_start : BOOLEAN;
    signal ap_frp_vld_in : STD_LOGIC;
    signal frp_pipeline_valid_U_exitcond : STD_LOGIC;
    signal pf_all_done : STD_LOGIC := '0';
    signal ap_ce_reg : STD_LOGIC;

    component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Infeasi_Res_S2_frp_fifoout IS
    generic (
        BlockingType : INTEGER;
        PipeLatency : INTEGER;
        PipelineII : INTEGER;
        DataWidth : INTEGER;
        NumWrites : INTEGER;
        CeilLog2Stages : INTEGER;
        CeilLog2FDepth : INTEGER;
        PfAllDoneEnable : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        valid : IN STD_LOGIC_VECTOR (59 downto 0);
        data_in_vld : IN STD_LOGIC;
        data_out_vld : OUT STD_LOGIC;
        data_in_last : IN STD_LOGIC;
        pf_continue : IN STD_LOGIC;
        pf_all_done : IN STD_LOGIC;
        pf_ready : OUT STD_LOGIC;
        pf_done : OUT STD_LOGIC;
        data_out_read : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        num_valid_datasets : IN STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component Infeasi_Res_S2_frp_pipeline_valid IS
    generic (
        PipelineLatency : INTEGER;
        PipelineII : INTEGER;
        CeilLog2Stages : INTEGER;
        ExitLatency : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        valid_in : IN STD_LOGIC;
        exitcond : IN STD_LOGIC;
        valid_out : OUT STD_LOGIC_VECTOR (59 downto 0);
        num_valid_datasets : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    ddiv_64ns_64ns_64_58_no_dsp_1_U547 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_97_p0,
        din1 => grp_fu_97_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_97_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U548 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_101_p0,
        din1 => grp_fu_101_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_101_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U549 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_105_p0,
        din1 => grp_fu_105_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_105_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U550 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_109_p0,
        din1 => grp_fu_109_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_109_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U551 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_113_p0,
        din1 => grp_fu_113_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_113_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U552 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_117_p0,
        din1 => grp_fu_117_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_117_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U553 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_121_p0,
        din1 => grp_fu_121_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_121_p2);

    ddiv_64ns_64ns_64_58_no_dsp_1_U554 : component Infeasi_Res_S2_ddiv_64ns_64ns_64_58_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 58,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_125_p0,
        din1 => grp_fu_125_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_125_p2);

    flow_control_loop_pipe_sequential_init_U : component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => pf_all_done,
        ap_continue_int => ap_continue_int,
        ap_done_int => pf_all_done);

    frp_pipeline_valid_U : component Infeasi_Res_S2_frp_pipeline_valid
    generic map (
        PipelineLatency => 60,
        PipelineII => 1,
        CeilLog2Stages => 6,
        ExitLatency => 0)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        valid_in => ap_frp_vld_in,
        exitcond => frp_pipeline_valid_U_exitcond,
        valid_out => frp_pipeline_valid_U_valid_out,
        num_valid_datasets => frp_pipeline_valid_U_num_valid_datasets);

    pf_temp_lb_U : component Infeasi_Res_S2_frp_fifoout
    generic map (
        BlockingType => 1,
        PipeLatency => 60,
        PipelineII => 1,
        DataWidth => 512,
        NumWrites => 1,
        CeilLog2Stages => 6,
        CeilLog2FDepth => 6,
        PfAllDoneEnable => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => or_ln426_s_fu_489_p9,
        data_out => pf_temp_lb_U_data_out,
        valid => frp_pipeline_valid_U_valid_out,
        data_in_vld => temp_lb_write_local,
        data_out_vld => pf_temp_lb_U_data_out_vld,
        data_in_last => ap_done_int_frp,
        pf_continue => ap_const_logic_1,
        pf_all_done => pf_all_done,
        pf_ready => pf_temp_lb_U_pf_ready,
        pf_done => pf_temp_lb_U_pf_done,
        data_out_read => temp_lb_full_n,
        ap_start => ap_const_logic_0,
        num_valid_datasets => frp_pipeline_valid_U_num_valid_datasets);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_frp_data_req_colScale_fifo_lb_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_frp_data_req_colScale_fifo_lb <= ap_const_lv6_0;
            else
                if ((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_0)) then 
                    ap_frp_data_req_colScale_fifo_lb <= std_logic_vector(unsigned(ap_frp_data_req_colScale_fifo_lb) - unsigned(ap_frp_data_next_issued_colScale_fifo_lb));
                else 
                    ap_frp_data_req_colScale_fifo_lb <= std_logic_vector(unsigned(std_logic_vector(unsigned(ap_frp_data_req_colScale_fifo_lb) + unsigned(ap_frp_data_req_colScale_fifo_lb_op93))) - unsigned(ap_frp_data_next_issued_colScale_fifo_lb));
                end if; 
            end if;
        end if;
    end process;


    ap_frp_data_req_primalInfeasBound_edotfifo_lb_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_frp_data_req_primalInfeasBound_edotfifo_lb <= ap_const_lv6_0;
            else
                if ((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_0)) then 
                    ap_frp_data_req_primalInfeasBound_edotfifo_lb <= std_logic_vector(unsigned(ap_frp_data_req_primalInfeasBound_edotfifo_lb) - unsigned(ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb));
                else 
                    ap_frp_data_req_primalInfeasBound_edotfifo_lb <= std_logic_vector(unsigned(std_logic_vector(unsigned(ap_frp_data_req_primalInfeasBound_edotfifo_lb) + unsigned(ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83))) - unsigned(ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb));
                end if; 
            end if;
        end if;
    end process;


    pf_all_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                pf_all_done <= ap_const_logic_0;
            else
                pf_all_done <= (pf_temp_lb_U_pf_done);
            end if;
        end if;
    end process;


    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1) and ((icmp_ln416_fu_159_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                i_fu_68 <= add_ln416_fu_149_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_68 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
                ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
                ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
                ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
                ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
                ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
                ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
                ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
                ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
                ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
                ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
                ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
                ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
                ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter50_reg <= ap_loop_exit_ready_pp0_iter49_reg;
                ap_loop_exit_ready_pp0_iter51_reg <= ap_loop_exit_ready_pp0_iter50_reg;
                ap_loop_exit_ready_pp0_iter52_reg <= ap_loop_exit_ready_pp0_iter51_reg;
                ap_loop_exit_ready_pp0_iter53_reg <= ap_loop_exit_ready_pp0_iter52_reg;
                ap_loop_exit_ready_pp0_iter54_reg <= ap_loop_exit_ready_pp0_iter53_reg;
                ap_loop_exit_ready_pp0_iter55_reg <= ap_loop_exit_ready_pp0_iter54_reg;
                ap_loop_exit_ready_pp0_iter56_reg <= ap_loop_exit_ready_pp0_iter55_reg;
                ap_loop_exit_ready_pp0_iter57_reg <= ap_loop_exit_ready_pp0_iter56_reg;
                ap_loop_exit_ready_pp0_iter58_reg <= ap_loop_exit_ready_pp0_iter57_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln418_1_reg_533 <= primalInfeasBound_edotfifo_lb_dout(127 downto 64);
                trunc_ln418_2_reg_538 <= primalInfeasBound_edotfifo_lb_dout(191 downto 128);
                trunc_ln418_3_reg_543 <= primalInfeasBound_edotfifo_lb_dout(255 downto 192);
                trunc_ln418_4_reg_548 <= primalInfeasBound_edotfifo_lb_dout(319 downto 256);
                trunc_ln418_5_reg_553 <= primalInfeasBound_edotfifo_lb_dout(383 downto 320);
                trunc_ln418_6_reg_558 <= primalInfeasBound_edotfifo_lb_dout(447 downto 384);
                trunc_ln418_7_reg_563 <= primalInfeasBound_edotfifo_lb_dout(511 downto 448);
                trunc_ln418_reg_528 <= trunc_ln418_fu_179_p1;
                trunc_ln419_1_reg_573 <= colScale_fifo_lb_dout(127 downto 64);
                trunc_ln419_2_reg_578 <= colScale_fifo_lb_dout(191 downto 128);
                trunc_ln419_3_reg_583 <= colScale_fifo_lb_dout(255 downto 192);
                trunc_ln419_4_reg_588 <= colScale_fifo_lb_dout(319 downto 256);
                trunc_ln419_5_reg_593 <= colScale_fifo_lb_dout(383 downto 320);
                trunc_ln419_6_reg_598 <= colScale_fifo_lb_dout(447 downto 384);
                trunc_ln419_7_reg_603 <= colScale_fifo_lb_dout(511 downto 448);
                trunc_ln419_reg_568 <= trunc_ln419_fu_255_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln416_fu_149_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_block_pp0_stage0 <= ap_const_boolean_0;
    ap_block_pp0_stage0_01001 <= ap_const_boolean_0;
    ap_block_pp0_stage0_11001 <= ap_const_boolean_0;
    ap_block_pp0_stage0_subdone <= ap_const_boolean_0;
        ap_block_state2_pp0_stage0_iter1 <= (ap_const_logic_1 = ap_const_logic_0);
        ap_block_state60_pp0_stage0_iter59 <= (ap_const_logic_1 = ap_const_logic_0);

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_block_pp0_stage0_subdone, icmp_ln416_fu_159_p2, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1) and ((icmp_ln416_fu_159_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_frp_pvb_no_bkwd_prs_assign_proc : process(pf_temp_lb_U_pf_ready)
    begin
                ap_condition_frp_pvb_no_bkwd_prs <= (pf_temp_lb_U_pf_ready = ap_const_logic_1);
    end process;


    ap_condition_frp_pvb_pf_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_start_int)
    begin
                ap_condition_frp_pvb_pf_start <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_1));
    end process;


    ap_condition_frp_roi_pvb_no_fwd_prs_assign_proc : process(primalInfeasBound_edotfifo_lb_num_data_valid, colScale_fifo_lb_num_data_valid, ap_frp_data_req_primalInfeasBound_edotfifo_lb, ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83, ap_frp_data_req_colScale_fifo_lb, ap_frp_data_req_colScale_fifo_lb_op93)
    begin
                ap_condition_frp_roi_pvb_no_fwd_prs <= not(((unsigned(colScale_fifo_lb_num_data_valid) < unsigned(std_logic_vector(unsigned(ap_frp_data_req_colScale_fifo_lb) + unsigned(ap_frp_data_req_colScale_fifo_lb_op93)))) or (unsigned(primalInfeasBound_edotfifo_lb_num_data_valid) < unsigned(std_logic_vector(unsigned(ap_frp_data_req_primalInfeasBound_edotfifo_lb) + unsigned(ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83))))));
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_frp_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter58_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter58_reg = ap_const_logic_1))) then 
            ap_done_int_frp <= ap_const_logic_1;
        else 
            ap_done_int_frp <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_reg_pp0_iter1_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(10) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter10 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(11) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter11 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(12) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter12 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(13) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter13 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(14) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter14 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(15) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter15 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(16) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter16 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(17) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter17 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(18) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter18 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(19) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter19 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(2) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter2 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(20) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter20 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(21) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter21 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(22) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter22 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(23) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter23 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(24) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter24 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(25) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter25 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(26) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter26 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(27) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter27 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(28) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter28 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(29) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter29 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(3) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter3 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(30) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter30 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(31) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter31 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(32) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter32 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(33) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter33 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(34) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter34 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(35) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter35 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(36) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter36 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter37_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(37) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter37 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter37 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter38_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(38) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter38 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter38 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter39_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(39) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter39 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter39 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(4) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter4 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter40_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(40) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter40 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter40 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter41_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(41) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter41 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter41 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter42_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(42) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter42 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter42 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter43_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(43) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter43 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter43 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter44_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(44) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter44 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter44 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter45_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(45) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter45 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter45 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter46_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(46) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter46 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter46 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter47_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(47) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter47 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter47 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter48_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(48) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter48 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter48 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter49_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(49) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter49 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter49 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(5) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter5 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter50_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(50) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter50 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter50 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter51_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(51) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter51 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter51 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter52_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(52) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter52 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter52 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter53_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(53) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter53 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter53 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter54_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(54) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter54 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter54 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter55_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(55) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter55 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter55 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter56_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(56) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter56 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter56 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter57_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(57) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter57 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter57 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter58_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(58) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter58 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter58 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter59_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(59) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter59 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter59 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(6) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter6 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(7) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter7 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(8) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter8 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(9) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter9 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_issued_nxt_colScale_fifo_lb_op93_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_frp_data_issued_nxt_colScale_fifo_lb_op93 <= ap_const_logic_1;
        else 
            ap_frp_data_issued_nxt_colScale_fifo_lb_op93 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83 <= ap_const_logic_1;
        else 
            ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_next_issued_colScale_fifo_lb_assign_proc : process(ap_frp_data_issued_nxt_colScale_fifo_lb_op93)
    begin
        if ((ap_frp_data_issued_nxt_colScale_fifo_lb_op93 = ap_const_logic_1)) then 
            ap_frp_data_next_issued_colScale_fifo_lb <= ap_const_lv1_1;
        else 
            ap_frp_data_next_issued_colScale_fifo_lb <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb_assign_proc : process(ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83)
    begin
        if ((ap_frp_data_issued_nxt_primalInfeasBound_edotfifo_lb_op83 = ap_const_logic_1)) then 
            ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb <= ap_const_lv1_1;
        else 
            ap_frp_data_next_issued_primalInfeasBound_edotfifo_lb <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_req_colScale_fifo_lb_op93_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln416_fu_159_p2)
    begin
        if ((not((icmp_ln416_fu_159_p2 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_frp_data_req_colScale_fifo_lb_op93 <= ap_const_lv1_1;
        else 
            ap_frp_data_req_colScale_fifo_lb_op93 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln416_fu_159_p2)
    begin
        if ((not((icmp_ln416_fu_159_p2 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83 <= ap_const_lv1_1;
        else 
            ap_frp_data_req_primalInfeasBound_edotfifo_lb_op83 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_vld_in_assign_proc : process(ap_condition_frp_roi_pvb_no_fwd_prs, ap_condition_frp_pvb_no_bkwd_prs, ap_condition_frp_pvb_pf_start)
    begin
        if (((ap_const_boolean_1 = ap_condition_frp_pvb_pf_start) and (ap_const_boolean_1 = ap_condition_frp_pvb_no_bkwd_prs) and (ap_const_boolean_1 = ap_condition_frp_roi_pvb_no_fwd_prs))) then 
            ap_frp_vld_in <= ap_const_logic_1;
        else 
            ap_frp_vld_in <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_enable_reg_pp0_iter37, ap_enable_reg_pp0_iter38, ap_enable_reg_pp0_iter39, ap_enable_reg_pp0_iter40, ap_enable_reg_pp0_iter41, ap_enable_reg_pp0_iter42, ap_enable_reg_pp0_iter43, ap_enable_reg_pp0_iter44, ap_enable_reg_pp0_iter45, ap_enable_reg_pp0_iter46, ap_enable_reg_pp0_iter47, ap_enable_reg_pp0_iter48, ap_enable_reg_pp0_iter49, ap_enable_reg_pp0_iter50, ap_enable_reg_pp0_iter51, ap_enable_reg_pp0_iter52, ap_enable_reg_pp0_iter53, ap_enable_reg_pp0_iter54, ap_enable_reg_pp0_iter55, ap_enable_reg_pp0_iter56, ap_enable_reg_pp0_iter57, ap_enable_reg_pp0_iter58, ap_enable_reg_pp0_iter59)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter59 = ap_const_logic_0) and (ap_enable_reg_pp0_iter58 = ap_const_logic_0) and (ap_enable_reg_pp0_iter57 = ap_const_logic_0) and (ap_enable_reg_pp0_iter56 = ap_const_logic_0) and (ap_enable_reg_pp0_iter55 = ap_const_logic_0) and (ap_enable_reg_pp0_iter54 = ap_const_logic_0) and (ap_enable_reg_pp0_iter53 = ap_const_logic_0) and (ap_enable_reg_pp0_iter52 = ap_const_logic_0) and (ap_enable_reg_pp0_iter51 = ap_const_logic_0) and (ap_enable_reg_pp0_iter50 = ap_const_logic_0) and (ap_enable_reg_pp0_iter49 = ap_const_logic_0) and (ap_enable_reg_pp0_iter48 = ap_const_logic_0) and (ap_enable_reg_pp0_iter47 = ap_const_logic_0) and (ap_enable_reg_pp0_iter46 = ap_const_logic_0) and (ap_enable_reg_pp0_iter45 
    = ap_const_logic_0) and (ap_enable_reg_pp0_iter44 = ap_const_logic_0) and (ap_enable_reg_pp0_iter43 = ap_const_logic_0) and (ap_enable_reg_pp0_iter42 = ap_const_logic_0) and (ap_enable_reg_pp0_iter41 = ap_const_logic_0) and (ap_enable_reg_pp0_iter40 = ap_const_logic_0) and (ap_enable_reg_pp0_iter39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter38 = ap_const_logic_0) and (ap_enable_reg_pp0_iter37 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_block_pp0_stage0_subdone, frp_pipeline_valid_U_valid_out)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_68, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_68;
        end if; 
    end process;

    bitcast_ln426_1_fu_461_p1 <= grp_fu_101_p2;
    bitcast_ln426_2_fu_465_p1 <= grp_fu_105_p2;
    bitcast_ln426_3_fu_469_p1 <= grp_fu_109_p2;
    bitcast_ln426_4_fu_473_p1 <= grp_fu_113_p2;
    bitcast_ln426_5_fu_477_p1 <= grp_fu_117_p2;
    bitcast_ln426_6_fu_481_p1 <= grp_fu_121_p2;
    bitcast_ln426_7_fu_485_p1 <= grp_fu_125_p2;
    bitcast_ln426_fu_457_p1 <= grp_fu_97_p2;
    colScale_fifo_lb_blk_n <= ap_const_logic_1;
    colScale_fifo_lb_read <= colScale_fifo_lb_read_local;

    colScale_fifo_lb_read_local_assign_proc : process(ap_block_pp0_stage0_11001, frp_pipeline_valid_U_valid_out)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1))) then 
            colScale_fifo_lb_read_local <= ap_const_logic_1;
        else 
            colScale_fifo_lb_read_local <= ap_const_logic_0;
        end if; 
    end process;


    frp_pipeline_valid_U_exitcond_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln416_fu_159_p2)
    begin
        if (((icmp_ln416_fu_159_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            frp_pipeline_valid_U_exitcond <= ap_const_logic_1;
        else 
            frp_pipeline_valid_U_exitcond <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_101_p0 <= trunc_ln418_1_reg_533;
    grp_fu_101_p1 <= trunc_ln419_1_reg_573;
    grp_fu_105_p0 <= trunc_ln418_2_reg_538;
    grp_fu_105_p1 <= trunc_ln419_2_reg_578;
    grp_fu_109_p0 <= trunc_ln418_3_reg_543;
    grp_fu_109_p1 <= trunc_ln419_3_reg_583;
    grp_fu_113_p0 <= trunc_ln418_4_reg_548;
    grp_fu_113_p1 <= trunc_ln419_4_reg_588;
    grp_fu_117_p0 <= trunc_ln418_5_reg_553;
    grp_fu_117_p1 <= trunc_ln419_5_reg_593;
    grp_fu_121_p0 <= trunc_ln418_6_reg_558;
    grp_fu_121_p1 <= trunc_ln419_6_reg_598;
    grp_fu_125_p0 <= trunc_ln418_7_reg_563;
    grp_fu_125_p1 <= trunc_ln419_7_reg_603;
    grp_fu_97_p0 <= trunc_ln418_reg_528;
    grp_fu_97_p1 <= trunc_ln419_reg_568;
    icmp_ln416_fu_159_p2 <= "1" when (signed(zext_ln413_fu_155_p1) < signed(n_6)) else "0";
    or_ln426_s_fu_489_p9 <= (((((((bitcast_ln426_7_fu_485_p1 & bitcast_ln426_6_fu_481_p1) & bitcast_ln426_5_fu_477_p1) & bitcast_ln426_4_fu_473_p1) & bitcast_ln426_3_fu_469_p1) & bitcast_ln426_2_fu_465_p1) & bitcast_ln426_1_fu_461_p1) & bitcast_ln426_fu_457_p1);
    primalInfeasBound_edotfifo_lb_blk_n <= ap_const_logic_1;
    primalInfeasBound_edotfifo_lb_read <= primalInfeasBound_edotfifo_lb_read_local;

    primalInfeasBound_edotfifo_lb_read_local_assign_proc : process(ap_block_pp0_stage0_11001, frp_pipeline_valid_U_valid_out)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1))) then 
            primalInfeasBound_edotfifo_lb_read_local <= ap_const_logic_1;
        else 
            primalInfeasBound_edotfifo_lb_read_local <= ap_const_logic_0;
        end if; 
    end process;

    temp_lb_blk_n <= ap_const_logic_1;
    temp_lb_din <= pf_temp_lb_U_data_out;

    temp_lb_write_assign_proc : process(pf_temp_lb_U_data_out_vld)
    begin
        if ((pf_temp_lb_U_data_out_vld = ap_const_logic_1)) then 
            temp_lb_write <= ap_const_logic_1;
        else 
            temp_lb_write <= ap_const_logic_0;
        end if; 
    end process;


    temp_lb_write_local_assign_proc : process(ap_enable_reg_pp0_iter59, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter59 = ap_const_logic_1))) then 
            temp_lb_write_local <= ap_const_logic_1;
        else 
            temp_lb_write_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln418_fu_179_p1 <= primalInfeasBound_edotfifo_lb_dout(64 - 1 downto 0);
    trunc_ln419_fu_255_p1 <= colScale_fifo_lb_dout(64 - 1 downto 0);
    zext_ln413_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),32));
end behav;
