-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Infeasi_Res_S2_axpy_2fused_Pipeline_axpy_2fused is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    dualInfeasConstr_SVfifo_i_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    dualInfeasConstr_SVfifo_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasConstr_SVfifo_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasConstr_SVfifo_i_empty_n : IN STD_LOGIC;
    dualInfeasConstr_SVfifo_i_read : OUT STD_LOGIC;
    dualInfeasLbRay_SVfifo_i_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    dualInfeasLbRay_SVfifo_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasLbRay_SVfifo_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasLbRay_SVfifo_i_empty_n : IN STD_LOGIC;
    dualInfeasLbRay_SVfifo_i_read : OUT STD_LOGIC;
    dualInfeasUbRay_SVfifo_i_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    dualInfeasUbRay_SVfifo_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasUbRay_SVfifo_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasUbRay_SVfifo_i_empty_n : IN STD_LOGIC;
    dualInfeasUbRay_SVfifo_i_read : OUT STD_LOGIC;
    dualInfeasConstr_axpyfifo_i_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    dualInfeasConstr_axpyfifo_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasConstr_axpyfifo_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dualInfeasConstr_axpyfifo_i_full_n : IN STD_LOGIC;
    dualInfeasConstr_axpyfifo_i_write : OUT STD_LOGIC;
    nCols_assign_load : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Infeasi_Res_S2_axpy_2fused_Pipeline_axpy_2fused is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln302_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal dualInfeasConstr_SVfifo_i_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dualInfeasLbRay_SVfifo_i_blk_n : STD_LOGIC;
    signal dualInfeasUbRay_SVfifo_i_blk_n : STD_LOGIC;
    signal dualInfeasConstr_axpyfifo_i_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln304_fu_219_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_reg_732_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_7_reg_737_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_8_reg_742_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_9_reg_747_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_s_reg_752_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_1_reg_757_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_2_reg_762_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln304_3_reg_767_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_fu_369_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_1_fu_373_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_2_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_3_fu_381_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_4_fu_385_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_5_fu_389_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_6_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln305_7_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_1_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_2_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_3_fu_489_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_4_fu_493_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_5_fu_497_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_6_fu_501_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln306_7_fu_505_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_fu_573_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_1_fu_576_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_2_fu_579_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_3_fu_582_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_4_fu_585_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_5_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_6_fu_591_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln304_7_fu_594_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_129_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_133_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_70 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln302_fu_199_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (30 downto 0);
    signal dualInfeasConstr_SVfifo_i_read_local : STD_LOGIC;
    signal dualInfeasLbRay_SVfifo_i_read_local : STD_LOGIC;
    signal dualInfeasUbRay_SVfifo_i_read_local : STD_LOGIC;
    signal or_ln313_i_fu_693_p9 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dualInfeasConstr_axpyfifo_i_write_local : STD_LOGIC;
    signal grp_fu_105_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_129_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_129_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_133_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_133_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_137_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_137_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_141_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_141_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_145_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_145_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_149_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_149_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_153_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_153_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_157_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_157_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_161_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_165_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_165_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_fu_189_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln305_fu_295_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_7_fu_299_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_8_fu_309_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_9_fu_319_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_s_fu_329_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_1_fu_339_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_2_fu_349_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln305_3_fu_359_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_fu_403_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_7_fu_407_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_8_fu_417_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_9_fu_427_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_s_fu_437_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_1_fu_447_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_2_fu_457_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln306_3_fu_467_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_137_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_141_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_145_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_149_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_153_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_161_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_165_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_7_fu_689_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_6_fu_685_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_5_fu_681_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_4_fu_677_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_3_fu_673_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_2_fu_669_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_1_fu_665_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln313_fu_661_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_105_ce : STD_LOGIC;
    signal pre_grp_fu_105_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_105_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_109_ce : STD_LOGIC;
    signal pre_grp_fu_109_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_109_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_113_ce : STD_LOGIC;
    signal pre_grp_fu_113_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_113_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_117_ce : STD_LOGIC;
    signal pre_grp_fu_117_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_117_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_ce : STD_LOGIC;
    signal pre_grp_fu_121_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_121_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_125_ce : STD_LOGIC;
    signal pre_grp_fu_125_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_125_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_129_ce : STD_LOGIC;
    signal pre_grp_fu_129_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_129_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_133_ce : STD_LOGIC;
    signal pre_grp_fu_133_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_133_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_137_ce : STD_LOGIC;
    signal pre_grp_fu_137_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_137_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_141_ce : STD_LOGIC;
    signal pre_grp_fu_141_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_141_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_145_ce : STD_LOGIC;
    signal pre_grp_fu_145_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_145_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_149_ce : STD_LOGIC;
    signal pre_grp_fu_149_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_149_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_153_ce : STD_LOGIC;
    signal pre_grp_fu_153_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_153_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_157_ce : STD_LOGIC;
    signal pre_grp_fu_157_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_157_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_161_ce : STD_LOGIC;
    signal pre_grp_fu_161_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_161_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_165_ce : STD_LOGIC;
    signal pre_grp_fu_165_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_grp_fu_165_p2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_done_int_frp : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal frp_pipeline_valid_U_valid_out : STD_LOGIC_VECTOR (15 downto 0);
    signal frp_pipeline_valid_U_num_valid_datasets : STD_LOGIC_VECTOR (4 downto 0);
    signal pf_dualInfeasConstr_axpyfifo_i_U_data_out : STD_LOGIC_VECTOR (511 downto 0);
    signal pf_dualInfeasConstr_axpyfifo_i_U_data_out_vld : STD_LOGIC;
    signal pf_dualInfeasConstr_axpyfifo_i_U_pf_ready : STD_LOGIC;
    signal pf_dualInfeasConstr_axpyfifo_i_U_pf_done : STD_LOGIC;
    signal ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40 : STD_LOGIC;
    signal ap_frp_data_req_dualInfeasConstr_SVfifo_i : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50 : STD_LOGIC;
    signal ap_frp_data_req_dualInfeasLbRay_SVfifo_i : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68 : STD_LOGIC;
    signal ap_frp_data_req_dualInfeasUbRay_SVfifo_i : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_frp_roi_pvb_no_fwd_prs : BOOLEAN;
    signal ap_condition_frp_pvb_no_bkwd_prs : BOOLEAN;
    signal ap_condition_frp_pvb_pf_start : BOOLEAN;
    signal ap_frp_vld_in : STD_LOGIC;
    signal frp_pipeline_valid_U_exitcond : STD_LOGIC;
    signal pf_all_done : STD_LOGIC := '0';
    signal ap_ce_reg : STD_LOGIC;

    component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Infeasi_Res_S2_frp_fifoout IS
    generic (
        BlockingType : INTEGER;
        PipeLatency : INTEGER;
        PipelineII : INTEGER;
        DataWidth : INTEGER;
        NumWrites : INTEGER;
        CeilLog2Stages : INTEGER;
        CeilLog2FDepth : INTEGER;
        PfAllDoneEnable : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        valid : IN STD_LOGIC_VECTOR (15 downto 0);
        data_in_vld : IN STD_LOGIC;
        data_out_vld : OUT STD_LOGIC;
        data_in_last : IN STD_LOGIC;
        pf_continue : IN STD_LOGIC;
        pf_all_done : IN STD_LOGIC;
        pf_ready : OUT STD_LOGIC;
        pf_done : OUT STD_LOGIC;
        data_out_read : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        num_valid_datasets : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component Infeasi_Res_S2_frp_pipeline_valid IS
    generic (
        PipelineLatency : INTEGER;
        PipelineII : INTEGER;
        CeilLog2Stages : INTEGER;
        ExitLatency : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        valid_in : IN STD_LOGIC;
        exitcond : IN STD_LOGIC;
        valid_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        num_valid_datasets : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    dsub_64ns_64ns_64_7_no_dsp_1_U117 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_105_p0,
        din1 => grp_fu_105_p1,
        ce => grp_fu_105_ce,
        dout => pre_grp_fu_105_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U118 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_109_p0,
        din1 => grp_fu_109_p1,
        ce => grp_fu_109_ce,
        dout => pre_grp_fu_109_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U119 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_113_p0,
        din1 => grp_fu_113_p1,
        ce => grp_fu_113_ce,
        dout => pre_grp_fu_113_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U120 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_117_p0,
        din1 => grp_fu_117_p1,
        ce => grp_fu_117_ce,
        dout => pre_grp_fu_117_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U121 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_121_p0,
        din1 => grp_fu_121_p1,
        ce => grp_fu_121_ce,
        dout => pre_grp_fu_121_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U122 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_125_p0,
        din1 => grp_fu_125_p1,
        ce => grp_fu_125_ce,
        dout => pre_grp_fu_125_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U123 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_129_p0,
        din1 => grp_fu_129_p1,
        ce => grp_fu_129_ce,
        dout => pre_grp_fu_129_p2);

    dsub_64ns_64ns_64_7_no_dsp_1_U124 : component Infeasi_Res_S2_dsub_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_133_p0,
        din1 => grp_fu_133_p1,
        ce => grp_fu_133_ce,
        dout => pre_grp_fu_133_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U125 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_137_p0,
        din1 => grp_fu_137_p1,
        ce => grp_fu_137_ce,
        dout => pre_grp_fu_137_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U126 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_141_p0,
        din1 => grp_fu_141_p1,
        ce => grp_fu_141_ce,
        dout => pre_grp_fu_141_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U127 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_145_p0,
        din1 => grp_fu_145_p1,
        ce => grp_fu_145_ce,
        dout => pre_grp_fu_145_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U128 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_149_p0,
        din1 => grp_fu_149_p1,
        ce => grp_fu_149_ce,
        dout => pre_grp_fu_149_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U129 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_153_p0,
        din1 => grp_fu_153_p1,
        ce => grp_fu_153_ce,
        dout => pre_grp_fu_153_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U130 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_157_p0,
        din1 => grp_fu_157_p1,
        ce => grp_fu_157_ce,
        dout => pre_grp_fu_157_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U131 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_161_p0,
        din1 => grp_fu_161_p1,
        ce => grp_fu_161_ce,
        dout => pre_grp_fu_161_p2);

    dadd_64ns_64ns_64_7_no_dsp_1_U132 : component Infeasi_Res_S2_dadd_64ns_64ns_64_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_165_p0,
        din1 => grp_fu_165_p1,
        ce => grp_fu_165_ce,
        dout => pre_grp_fu_165_p2);

    flow_control_loop_pipe_sequential_init_U : component Infeasi_Res_S2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => pf_all_done,
        ap_continue_int => ap_continue_int,
        ap_done_int => pf_all_done);

    frp_pipeline_valid_U : component Infeasi_Res_S2_frp_pipeline_valid
    generic map (
        PipelineLatency => 16,
        PipelineII => 1,
        CeilLog2Stages => 4,
        ExitLatency => 0)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        valid_in => ap_frp_vld_in,
        exitcond => frp_pipeline_valid_U_exitcond,
        valid_out => frp_pipeline_valid_U_valid_out,
        num_valid_datasets => frp_pipeline_valid_U_num_valid_datasets);

    pf_dualInfeasConstr_axpyfifo_i_U : component Infeasi_Res_S2_frp_fifoout
    generic map (
        BlockingType => 1,
        PipeLatency => 16,
        PipelineII => 1,
        DataWidth => 512,
        NumWrites => 1,
        CeilLog2Stages => 4,
        CeilLog2FDepth => 5,
        PfAllDoneEnable => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => or_ln313_i_fu_693_p9,
        data_out => pf_dualInfeasConstr_axpyfifo_i_U_data_out,
        valid => frp_pipeline_valid_U_valid_out,
        data_in_vld => dualInfeasConstr_axpyfifo_i_write_local,
        data_out_vld => pf_dualInfeasConstr_axpyfifo_i_U_data_out_vld,
        data_in_last => ap_done_int_frp,
        pf_continue => ap_const_logic_1,
        pf_all_done => pf_all_done,
        pf_ready => pf_dualInfeasConstr_axpyfifo_i_U_pf_ready,
        pf_done => pf_dualInfeasConstr_axpyfifo_i_U_pf_done,
        data_out_read => dualInfeasConstr_axpyfifo_i_full_n,
        ap_start => ap_const_logic_0,
        num_valid_datasets => frp_pipeline_valid_U_num_valid_datasets);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_frp_data_req_dualInfeasConstr_SVfifo_i_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_frp_data_req_dualInfeasConstr_SVfifo_i <= ap_const_lv4_0;
            else
                if ((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_0)) then 
                    ap_frp_data_req_dualInfeasConstr_SVfifo_i <= std_logic_vector(unsigned(ap_frp_data_req_dualInfeasConstr_SVfifo_i) - unsigned(ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i));
                else 
                    ap_frp_data_req_dualInfeasConstr_SVfifo_i <= std_logic_vector(unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasConstr_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40))) - unsigned(ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i));
                end if; 
            end if;
        end if;
    end process;


    ap_frp_data_req_dualInfeasLbRay_SVfifo_i_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_frp_data_req_dualInfeasLbRay_SVfifo_i <= ap_const_lv4_0;
            else
                if ((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_0)) then 
                    ap_frp_data_req_dualInfeasLbRay_SVfifo_i <= std_logic_vector(unsigned(ap_frp_data_req_dualInfeasLbRay_SVfifo_i) - unsigned(ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i));
                else 
                    ap_frp_data_req_dualInfeasLbRay_SVfifo_i <= std_logic_vector(unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasLbRay_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50))) - unsigned(ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i));
                end if; 
            end if;
        end if;
    end process;


    ap_frp_data_req_dualInfeasUbRay_SVfifo_i_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_frp_data_req_dualInfeasUbRay_SVfifo_i <= ap_const_lv4_0;
            else
                if ((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_0)) then 
                    ap_frp_data_req_dualInfeasUbRay_SVfifo_i <= std_logic_vector(unsigned(ap_frp_data_req_dualInfeasUbRay_SVfifo_i) - unsigned(ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i));
                else 
                    ap_frp_data_req_dualInfeasUbRay_SVfifo_i <= std_logic_vector(unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasUbRay_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68))) - unsigned(ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i));
                end if; 
            end if;
        end if;
    end process;


    pf_all_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                pf_all_done <= ap_const_logic_0;
            else
                pf_all_done <= (pf_dualInfeasConstr_axpyfifo_i_U_pf_done);
            end if;
        end if;
    end process;


    grp_fu_105_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_109_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_113_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_117_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_121_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_125_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_129_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_133_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_137_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_141_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_145_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_149_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_153_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_157_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_161_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    grp_fu_165_ce_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    i_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1) and ((icmp_ln302_fu_193_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                i_fu_70 <= add_ln302_fu_199_p2;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_fu_70 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                trunc_ln304_1_reg_757_pp0_iter2_reg <= trunc_ln304_1_reg_757;
                trunc_ln304_1_reg_757_pp0_iter3_reg <= trunc_ln304_1_reg_757_pp0_iter2_reg;
                trunc_ln304_1_reg_757_pp0_iter4_reg <= trunc_ln304_1_reg_757_pp0_iter3_reg;
                trunc_ln304_1_reg_757_pp0_iter5_reg <= trunc_ln304_1_reg_757_pp0_iter4_reg;
                trunc_ln304_1_reg_757_pp0_iter6_reg <= trunc_ln304_1_reg_757_pp0_iter5_reg;
                trunc_ln304_1_reg_757_pp0_iter7_reg <= trunc_ln304_1_reg_757_pp0_iter6_reg;
                trunc_ln304_2_reg_762_pp0_iter2_reg <= trunc_ln304_2_reg_762;
                trunc_ln304_2_reg_762_pp0_iter3_reg <= trunc_ln304_2_reg_762_pp0_iter2_reg;
                trunc_ln304_2_reg_762_pp0_iter4_reg <= trunc_ln304_2_reg_762_pp0_iter3_reg;
                trunc_ln304_2_reg_762_pp0_iter5_reg <= trunc_ln304_2_reg_762_pp0_iter4_reg;
                trunc_ln304_2_reg_762_pp0_iter6_reg <= trunc_ln304_2_reg_762_pp0_iter5_reg;
                trunc_ln304_2_reg_762_pp0_iter7_reg <= trunc_ln304_2_reg_762_pp0_iter6_reg;
                trunc_ln304_3_reg_767_pp0_iter2_reg <= trunc_ln304_3_reg_767;
                trunc_ln304_3_reg_767_pp0_iter3_reg <= trunc_ln304_3_reg_767_pp0_iter2_reg;
                trunc_ln304_3_reg_767_pp0_iter4_reg <= trunc_ln304_3_reg_767_pp0_iter3_reg;
                trunc_ln304_3_reg_767_pp0_iter5_reg <= trunc_ln304_3_reg_767_pp0_iter4_reg;
                trunc_ln304_3_reg_767_pp0_iter6_reg <= trunc_ln304_3_reg_767_pp0_iter5_reg;
                trunc_ln304_3_reg_767_pp0_iter7_reg <= trunc_ln304_3_reg_767_pp0_iter6_reg;
                trunc_ln304_7_reg_737_pp0_iter2_reg <= trunc_ln304_7_reg_737;
                trunc_ln304_7_reg_737_pp0_iter3_reg <= trunc_ln304_7_reg_737_pp0_iter2_reg;
                trunc_ln304_7_reg_737_pp0_iter4_reg <= trunc_ln304_7_reg_737_pp0_iter3_reg;
                trunc_ln304_7_reg_737_pp0_iter5_reg <= trunc_ln304_7_reg_737_pp0_iter4_reg;
                trunc_ln304_7_reg_737_pp0_iter6_reg <= trunc_ln304_7_reg_737_pp0_iter5_reg;
                trunc_ln304_7_reg_737_pp0_iter7_reg <= trunc_ln304_7_reg_737_pp0_iter6_reg;
                trunc_ln304_8_reg_742_pp0_iter2_reg <= trunc_ln304_8_reg_742;
                trunc_ln304_8_reg_742_pp0_iter3_reg <= trunc_ln304_8_reg_742_pp0_iter2_reg;
                trunc_ln304_8_reg_742_pp0_iter4_reg <= trunc_ln304_8_reg_742_pp0_iter3_reg;
                trunc_ln304_8_reg_742_pp0_iter5_reg <= trunc_ln304_8_reg_742_pp0_iter4_reg;
                trunc_ln304_8_reg_742_pp0_iter6_reg <= trunc_ln304_8_reg_742_pp0_iter5_reg;
                trunc_ln304_8_reg_742_pp0_iter7_reg <= trunc_ln304_8_reg_742_pp0_iter6_reg;
                trunc_ln304_9_reg_747_pp0_iter2_reg <= trunc_ln304_9_reg_747;
                trunc_ln304_9_reg_747_pp0_iter3_reg <= trunc_ln304_9_reg_747_pp0_iter2_reg;
                trunc_ln304_9_reg_747_pp0_iter4_reg <= trunc_ln304_9_reg_747_pp0_iter3_reg;
                trunc_ln304_9_reg_747_pp0_iter5_reg <= trunc_ln304_9_reg_747_pp0_iter4_reg;
                trunc_ln304_9_reg_747_pp0_iter6_reg <= trunc_ln304_9_reg_747_pp0_iter5_reg;
                trunc_ln304_9_reg_747_pp0_iter7_reg <= trunc_ln304_9_reg_747_pp0_iter6_reg;
                trunc_ln304_reg_732_pp0_iter2_reg <= trunc_ln304_reg_732;
                trunc_ln304_reg_732_pp0_iter3_reg <= trunc_ln304_reg_732_pp0_iter2_reg;
                trunc_ln304_reg_732_pp0_iter4_reg <= trunc_ln304_reg_732_pp0_iter3_reg;
                trunc_ln304_reg_732_pp0_iter5_reg <= trunc_ln304_reg_732_pp0_iter4_reg;
                trunc_ln304_reg_732_pp0_iter6_reg <= trunc_ln304_reg_732_pp0_iter5_reg;
                trunc_ln304_reg_732_pp0_iter7_reg <= trunc_ln304_reg_732_pp0_iter6_reg;
                trunc_ln304_s_reg_752_pp0_iter2_reg <= trunc_ln304_s_reg_752;
                trunc_ln304_s_reg_752_pp0_iter3_reg <= trunc_ln304_s_reg_752_pp0_iter2_reg;
                trunc_ln304_s_reg_752_pp0_iter4_reg <= trunc_ln304_s_reg_752_pp0_iter3_reg;
                trunc_ln304_s_reg_752_pp0_iter5_reg <= trunc_ln304_s_reg_752_pp0_iter4_reg;
                trunc_ln304_s_reg_752_pp0_iter6_reg <= trunc_ln304_s_reg_752_pp0_iter5_reg;
                trunc_ln304_s_reg_752_pp0_iter7_reg <= trunc_ln304_s_reg_752_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln304_1_reg_757 <= dualInfeasConstr_SVfifo_i_dout(383 downto 320);
                trunc_ln304_2_reg_762 <= dualInfeasConstr_SVfifo_i_dout(447 downto 384);
                trunc_ln304_3_reg_767 <= dualInfeasConstr_SVfifo_i_dout(511 downto 448);
                trunc_ln304_7_reg_737 <= dualInfeasConstr_SVfifo_i_dout(127 downto 64);
                trunc_ln304_8_reg_742 <= dualInfeasConstr_SVfifo_i_dout(191 downto 128);
                trunc_ln304_9_reg_747 <= dualInfeasConstr_SVfifo_i_dout(255 downto 192);
                trunc_ln304_reg_732 <= trunc_ln304_fu_219_p1;
                trunc_ln304_s_reg_752 <= dualInfeasConstr_SVfifo_i_dout(319 downto 256);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
                grp_fu_105_p0 <= bitcast_ln305_fu_369_p1;
                grp_fu_105_p1 <= bitcast_ln306_fu_477_p1;
                grp_fu_109_p0 <= bitcast_ln305_1_fu_373_p1;
                grp_fu_109_p1 <= bitcast_ln306_1_fu_481_p1;
                grp_fu_113_p0 <= bitcast_ln305_2_fu_377_p1;
                grp_fu_113_p1 <= bitcast_ln306_2_fu_485_p1;
                grp_fu_117_p0 <= bitcast_ln305_3_fu_381_p1;
                grp_fu_117_p1 <= bitcast_ln306_3_fu_489_p1;
                grp_fu_121_p0 <= bitcast_ln305_4_fu_385_p1;
                grp_fu_121_p1 <= bitcast_ln306_4_fu_493_p1;
                grp_fu_125_p0 <= bitcast_ln305_5_fu_389_p1;
                grp_fu_125_p1 <= bitcast_ln306_5_fu_497_p1;
                grp_fu_129_p0 <= bitcast_ln305_6_fu_393_p1;
                grp_fu_129_p1 <= bitcast_ln306_6_fu_501_p1;
                grp_fu_133_p0 <= bitcast_ln305_7_fu_397_p1;
                grp_fu_133_p1 <= bitcast_ln306_7_fu_505_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then
                grp_fu_137_p0 <= bitcast_ln304_fu_573_p1;
                grp_fu_137_p1 <= grp_fu_105_p2;
                grp_fu_141_p0 <= bitcast_ln304_1_fu_576_p1;
                grp_fu_141_p1 <= grp_fu_109_p2;
                grp_fu_145_p0 <= bitcast_ln304_2_fu_579_p1;
                grp_fu_145_p1 <= grp_fu_113_p2;
                grp_fu_149_p0 <= bitcast_ln304_3_fu_582_p1;
                grp_fu_149_p1 <= grp_fu_117_p2;
                grp_fu_153_p0 <= bitcast_ln304_4_fu_585_p1;
                grp_fu_153_p1 <= grp_fu_121_p2;
                grp_fu_157_p0 <= bitcast_ln304_5_fu_588_p1;
                grp_fu_157_p1 <= grp_fu_125_p2;
                grp_fu_161_p0 <= bitcast_ln304_6_fu_591_p1;
                grp_fu_161_p1 <= grp_fu_129_p2;
                grp_fu_165_p0 <= bitcast_ln304_7_fu_594_p1;
                grp_fu_165_p1 <= grp_fu_133_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_105_ce = ap_const_logic_1)) then
                pre_grp_fu_105_p2_reg <= pre_grp_fu_105_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_109_ce = ap_const_logic_1)) then
                pre_grp_fu_109_p2_reg <= pre_grp_fu_109_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_113_ce = ap_const_logic_1)) then
                pre_grp_fu_113_p2_reg <= pre_grp_fu_113_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_117_ce = ap_const_logic_1)) then
                pre_grp_fu_117_p2_reg <= pre_grp_fu_117_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_121_ce = ap_const_logic_1)) then
                pre_grp_fu_121_p2_reg <= pre_grp_fu_121_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_125_ce = ap_const_logic_1)) then
                pre_grp_fu_125_p2_reg <= pre_grp_fu_125_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_129_ce = ap_const_logic_1)) then
                pre_grp_fu_129_p2_reg <= pre_grp_fu_129_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_133_ce = ap_const_logic_1)) then
                pre_grp_fu_133_p2_reg <= pre_grp_fu_133_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_137_ce = ap_const_logic_1)) then
                pre_grp_fu_137_p2_reg <= pre_grp_fu_137_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_141_ce = ap_const_logic_1)) then
                pre_grp_fu_141_p2_reg <= pre_grp_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_145_ce = ap_const_logic_1)) then
                pre_grp_fu_145_p2_reg <= pre_grp_fu_145_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_149_ce = ap_const_logic_1)) then
                pre_grp_fu_149_p2_reg <= pre_grp_fu_149_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_153_ce = ap_const_logic_1)) then
                pre_grp_fu_153_p2_reg <= pre_grp_fu_153_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_157_ce = ap_const_logic_1)) then
                pre_grp_fu_157_p2_reg <= pre_grp_fu_157_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_161_ce = ap_const_logic_1)) then
                pre_grp_fu_161_p2_reg <= pre_grp_fu_161_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((grp_fu_165_ce = ap_const_logic_1)) then
                pre_grp_fu_165_p2_reg <= pre_grp_fu_165_p2;
            end if;
        end if;
    end process;
    grp_fu_105_ce <= '1';
    grp_fu_109_ce <= '1';
    grp_fu_113_ce <= '1';
    grp_fu_117_ce <= '1';
    grp_fu_121_ce <= '1';
    grp_fu_125_ce <= '1';
    grp_fu_129_ce <= '1';
    grp_fu_133_ce <= '1';
    grp_fu_137_ce <= '1';
    grp_fu_141_ce <= '1';
    grp_fu_145_ce <= '1';
    grp_fu_149_ce <= '1';
    grp_fu_153_ce <= '1';
    grp_fu_157_ce <= '1';
    grp_fu_161_ce <= '1';
    grp_fu_165_ce <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln302_fu_199_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_block_pp0_stage0 <= ap_const_boolean_0;
    ap_block_pp0_stage0_01001 <= ap_const_boolean_0;
    ap_block_pp0_stage0_11001 <= ap_const_boolean_0;
    ap_block_pp0_stage0_subdone <= ap_const_boolean_0;
        ap_block_state16_pp0_stage0_iter15 <= (ap_const_logic_1 = ap_const_logic_0);
        ap_block_state2_pp0_stage0_iter1 <= (ap_const_logic_1 = ap_const_logic_0);

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_block_pp0_stage0_subdone, icmp_ln302_fu_193_p2, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1) and ((icmp_ln302_fu_193_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_frp_pvb_no_bkwd_prs_assign_proc : process(pf_dualInfeasConstr_axpyfifo_i_U_pf_ready)
    begin
                ap_condition_frp_pvb_no_bkwd_prs <= (pf_dualInfeasConstr_axpyfifo_i_U_pf_ready = ap_const_logic_1);
    end process;


    ap_condition_frp_pvb_pf_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_start_int)
    begin
                ap_condition_frp_pvb_pf_start <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_frp_roi_pvb_no_fwd_prs_assign_proc : process(dualInfeasConstr_SVfifo_i_num_data_valid, dualInfeasLbRay_SVfifo_i_num_data_valid, dualInfeasUbRay_SVfifo_i_num_data_valid, ap_frp_data_req_dualInfeasConstr_SVfifo_i, ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40, ap_frp_data_req_dualInfeasLbRay_SVfifo_i, ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50, ap_frp_data_req_dualInfeasUbRay_SVfifo_i, ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68)
    begin
                ap_condition_frp_roi_pvb_no_fwd_prs <= not(((unsigned(dualInfeasUbRay_SVfifo_i_num_data_valid) < unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasUbRay_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68)))) or (unsigned(dualInfeasLbRay_SVfifo_i_num_data_valid) < unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasLbRay_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50)))) or (unsigned(dualInfeasConstr_SVfifo_i_num_data_valid) < unsigned(std_logic_vector(unsigned(ap_frp_data_req_dualInfeasConstr_SVfifo_i) + unsigned(ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40))))));
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_frp_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter14_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int_frp <= ap_const_logic_1;
        else 
            ap_done_int_frp <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_reg_pp0_iter1_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(10) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter10 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(11) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter11 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(12) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter12 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(13) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter13 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(14) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter14 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(15) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter15 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(2) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter2 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(3) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter3 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(4) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter4 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(5) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter5 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(6) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter6 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(7) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter7 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(8) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter8 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(9) = ap_const_logic_1)) then 
            ap_enable_reg_pp0_iter9 <= ap_const_logic_1;
        else 
            ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40 <= ap_const_logic_1;
        else 
            ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50 <= ap_const_logic_1;
        else 
            ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68_assign_proc : process(frp_pipeline_valid_U_valid_out)
    begin
        if ((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1)) then 
            ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68 <= ap_const_logic_1;
        else 
            ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68 <= ap_const_logic_0;
        end if; 
    end process;


    ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i_assign_proc : process(ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40)
    begin
        if ((ap_frp_data_issued_nxt_dualInfeasConstr_SVfifo_i_op40 = ap_const_logic_1)) then 
            ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i <= ap_const_lv1_1;
        else 
            ap_frp_data_next_issued_dualInfeasConstr_SVfifo_i <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i_assign_proc : process(ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50)
    begin
        if ((ap_frp_data_issued_nxt_dualInfeasLbRay_SVfifo_i_op50 = ap_const_logic_1)) then 
            ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i <= ap_const_lv1_1;
        else 
            ap_frp_data_next_issued_dualInfeasLbRay_SVfifo_i <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i_assign_proc : process(ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68)
    begin
        if ((ap_frp_data_issued_nxt_dualInfeasUbRay_SVfifo_i_op68 = ap_const_logic_1)) then 
            ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i <= ap_const_lv1_1;
        else 
            ap_frp_data_next_issued_dualInfeasUbRay_SVfifo_i <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln302_fu_193_p2)
    begin
        if ((not((icmp_ln302_fu_193_p2 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40 <= ap_const_lv1_1;
        else 
            ap_frp_data_req_dualInfeasConstr_SVfifo_i_op40 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln302_fu_193_p2)
    begin
        if ((not((icmp_ln302_fu_193_p2 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50 <= ap_const_lv1_1;
        else 
            ap_frp_data_req_dualInfeasLbRay_SVfifo_i_op50 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln302_fu_193_p2)
    begin
        if ((not((icmp_ln302_fu_193_p2 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68 <= ap_const_lv1_1;
        else 
            ap_frp_data_req_dualInfeasUbRay_SVfifo_i_op68 <= ap_const_lv1_0;
        end if; 
    end process;


    ap_frp_vld_in_assign_proc : process(ap_condition_frp_roi_pvb_no_fwd_prs, ap_condition_frp_pvb_no_bkwd_prs, ap_condition_frp_pvb_pf_start)
    begin
        if (((ap_const_boolean_1 = ap_condition_frp_pvb_pf_start) and (ap_const_boolean_1 = ap_condition_frp_pvb_no_bkwd_prs) and (ap_const_boolean_1 = ap_condition_frp_roi_pvb_no_fwd_prs))) then 
            ap_frp_vld_in <= ap_const_logic_1;
        else 
            ap_frp_vld_in <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_block_pp0_stage0_subdone, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(0) = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_70, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_70;
        end if; 
    end process;

    bitcast_ln304_1_fu_576_p1 <= trunc_ln304_7_reg_737_pp0_iter7_reg;
    bitcast_ln304_2_fu_579_p1 <= trunc_ln304_8_reg_742_pp0_iter7_reg;
    bitcast_ln304_3_fu_582_p1 <= trunc_ln304_9_reg_747_pp0_iter7_reg;
    bitcast_ln304_4_fu_585_p1 <= trunc_ln304_s_reg_752_pp0_iter7_reg;
    bitcast_ln304_5_fu_588_p1 <= trunc_ln304_1_reg_757_pp0_iter7_reg;
    bitcast_ln304_6_fu_591_p1 <= trunc_ln304_2_reg_762_pp0_iter7_reg;
    bitcast_ln304_7_fu_594_p1 <= trunc_ln304_3_reg_767_pp0_iter7_reg;
    bitcast_ln304_fu_573_p1 <= trunc_ln304_reg_732_pp0_iter7_reg;
    bitcast_ln305_1_fu_373_p1 <= trunc_ln305_7_fu_299_p4;
    bitcast_ln305_2_fu_377_p1 <= trunc_ln305_8_fu_309_p4;
    bitcast_ln305_3_fu_381_p1 <= trunc_ln305_9_fu_319_p4;
    bitcast_ln305_4_fu_385_p1 <= trunc_ln305_s_fu_329_p4;
    bitcast_ln305_5_fu_389_p1 <= trunc_ln305_1_fu_339_p4;
    bitcast_ln305_6_fu_393_p1 <= trunc_ln305_2_fu_349_p4;
    bitcast_ln305_7_fu_397_p1 <= trunc_ln305_3_fu_359_p4;
    bitcast_ln305_fu_369_p1 <= trunc_ln305_fu_295_p1;
    bitcast_ln306_1_fu_481_p1 <= trunc_ln306_7_fu_407_p4;
    bitcast_ln306_2_fu_485_p1 <= trunc_ln306_8_fu_417_p4;
    bitcast_ln306_3_fu_489_p1 <= trunc_ln306_9_fu_427_p4;
    bitcast_ln306_4_fu_493_p1 <= trunc_ln306_s_fu_437_p4;
    bitcast_ln306_5_fu_497_p1 <= trunc_ln306_1_fu_447_p4;
    bitcast_ln306_6_fu_501_p1 <= trunc_ln306_2_fu_457_p4;
    bitcast_ln306_7_fu_505_p1 <= trunc_ln306_3_fu_467_p4;
    bitcast_ln306_fu_477_p1 <= trunc_ln306_fu_403_p1;
    bitcast_ln313_1_fu_665_p1 <= grp_fu_141_p2;
    bitcast_ln313_2_fu_669_p1 <= grp_fu_145_p2;
    bitcast_ln313_3_fu_673_p1 <= grp_fu_149_p2;
    bitcast_ln313_4_fu_677_p1 <= grp_fu_153_p2;
    bitcast_ln313_5_fu_681_p1 <= grp_fu_157_p2;
    bitcast_ln313_6_fu_685_p1 <= grp_fu_161_p2;
    bitcast_ln313_7_fu_689_p1 <= grp_fu_165_p2;
    bitcast_ln313_fu_661_p1 <= grp_fu_137_p2;
    dualInfeasConstr_SVfifo_i_blk_n <= ap_const_logic_1;
    dualInfeasConstr_SVfifo_i_read <= dualInfeasConstr_SVfifo_i_read_local;

    dualInfeasConstr_SVfifo_i_read_local_assign_proc : process(ap_block_pp0_stage0_11001, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dualInfeasConstr_SVfifo_i_read_local <= ap_const_logic_1;
        else 
            dualInfeasConstr_SVfifo_i_read_local <= ap_const_logic_0;
        end if; 
    end process;

    dualInfeasConstr_axpyfifo_i_blk_n <= ap_const_logic_1;
    dualInfeasConstr_axpyfifo_i_din <= pf_dualInfeasConstr_axpyfifo_i_U_data_out;

    dualInfeasConstr_axpyfifo_i_write_assign_proc : process(pf_dualInfeasConstr_axpyfifo_i_U_data_out_vld)
    begin
        if ((pf_dualInfeasConstr_axpyfifo_i_U_data_out_vld = ap_const_logic_1)) then 
            dualInfeasConstr_axpyfifo_i_write <= ap_const_logic_1;
        else 
            dualInfeasConstr_axpyfifo_i_write <= ap_const_logic_0;
        end if; 
    end process;


    dualInfeasConstr_axpyfifo_i_write_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dualInfeasConstr_axpyfifo_i_write_local <= ap_const_logic_1;
        else 
            dualInfeasConstr_axpyfifo_i_write_local <= ap_const_logic_0;
        end if; 
    end process;

    dualInfeasLbRay_SVfifo_i_blk_n <= ap_const_logic_1;
    dualInfeasLbRay_SVfifo_i_read <= dualInfeasLbRay_SVfifo_i_read_local;

    dualInfeasLbRay_SVfifo_i_read_local_assign_proc : process(ap_block_pp0_stage0_11001, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dualInfeasLbRay_SVfifo_i_read_local <= ap_const_logic_1;
        else 
            dualInfeasLbRay_SVfifo_i_read_local <= ap_const_logic_0;
        end if; 
    end process;

    dualInfeasUbRay_SVfifo_i_blk_n <= ap_const_logic_1;
    dualInfeasUbRay_SVfifo_i_read <= dualInfeasUbRay_SVfifo_i_read_local;

    dualInfeasUbRay_SVfifo_i_read_local_assign_proc : process(ap_block_pp0_stage0_11001, frp_pipeline_valid_U_valid_out)
    begin
        if (((frp_pipeline_valid_U_valid_out(1) = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dualInfeasUbRay_SVfifo_i_read_local <= ap_const_logic_1;
        else 
            dualInfeasUbRay_SVfifo_i_read_local <= ap_const_logic_0;
        end if; 
    end process;


    frp_pipeline_valid_U_exitcond_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln302_fu_193_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln302_fu_193_p2 = ap_const_lv1_0))) then 
            frp_pipeline_valid_U_exitcond <= ap_const_logic_1;
        else 
            frp_pipeline_valid_U_exitcond <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_105_p2_assign_proc : process(grp_fu_105_ce, pre_grp_fu_105_p2, pre_grp_fu_105_p2_reg)
    begin
        if ((grp_fu_105_ce = ap_const_logic_1)) then 
            grp_fu_105_p2 <= pre_grp_fu_105_p2;
        else 
            grp_fu_105_p2 <= pre_grp_fu_105_p2_reg;
        end if; 
    end process;


    grp_fu_109_p2_assign_proc : process(grp_fu_109_ce, pre_grp_fu_109_p2, pre_grp_fu_109_p2_reg)
    begin
        if ((grp_fu_109_ce = ap_const_logic_1)) then 
            grp_fu_109_p2 <= pre_grp_fu_109_p2;
        else 
            grp_fu_109_p2 <= pre_grp_fu_109_p2_reg;
        end if; 
    end process;


    grp_fu_113_p2_assign_proc : process(grp_fu_113_ce, pre_grp_fu_113_p2, pre_grp_fu_113_p2_reg)
    begin
        if ((grp_fu_113_ce = ap_const_logic_1)) then 
            grp_fu_113_p2 <= pre_grp_fu_113_p2;
        else 
            grp_fu_113_p2 <= pre_grp_fu_113_p2_reg;
        end if; 
    end process;


    grp_fu_117_p2_assign_proc : process(grp_fu_117_ce, pre_grp_fu_117_p2, pre_grp_fu_117_p2_reg)
    begin
        if ((grp_fu_117_ce = ap_const_logic_1)) then 
            grp_fu_117_p2 <= pre_grp_fu_117_p2;
        else 
            grp_fu_117_p2 <= pre_grp_fu_117_p2_reg;
        end if; 
    end process;


    grp_fu_121_p2_assign_proc : process(grp_fu_121_ce, pre_grp_fu_121_p2, pre_grp_fu_121_p2_reg)
    begin
        if ((grp_fu_121_ce = ap_const_logic_1)) then 
            grp_fu_121_p2 <= pre_grp_fu_121_p2;
        else 
            grp_fu_121_p2 <= pre_grp_fu_121_p2_reg;
        end if; 
    end process;


    grp_fu_125_p2_assign_proc : process(grp_fu_125_ce, pre_grp_fu_125_p2, pre_grp_fu_125_p2_reg)
    begin
        if ((grp_fu_125_ce = ap_const_logic_1)) then 
            grp_fu_125_p2 <= pre_grp_fu_125_p2;
        else 
            grp_fu_125_p2 <= pre_grp_fu_125_p2_reg;
        end if; 
    end process;


    grp_fu_129_p2_assign_proc : process(grp_fu_129_ce, pre_grp_fu_129_p2, pre_grp_fu_129_p2_reg)
    begin
        if ((grp_fu_129_ce = ap_const_logic_1)) then 
            grp_fu_129_p2 <= pre_grp_fu_129_p2;
        else 
            grp_fu_129_p2 <= pre_grp_fu_129_p2_reg;
        end if; 
    end process;


    grp_fu_133_p2_assign_proc : process(grp_fu_133_ce, pre_grp_fu_133_p2, pre_grp_fu_133_p2_reg)
    begin
        if ((grp_fu_133_ce = ap_const_logic_1)) then 
            grp_fu_133_p2 <= pre_grp_fu_133_p2;
        else 
            grp_fu_133_p2 <= pre_grp_fu_133_p2_reg;
        end if; 
    end process;


    grp_fu_137_p2_assign_proc : process(grp_fu_137_ce, pre_grp_fu_137_p2, pre_grp_fu_137_p2_reg)
    begin
        if ((grp_fu_137_ce = ap_const_logic_1)) then 
            grp_fu_137_p2 <= pre_grp_fu_137_p2;
        else 
            grp_fu_137_p2 <= pre_grp_fu_137_p2_reg;
        end if; 
    end process;


    grp_fu_141_p2_assign_proc : process(grp_fu_141_ce, pre_grp_fu_141_p2, pre_grp_fu_141_p2_reg)
    begin
        if ((grp_fu_141_ce = ap_const_logic_1)) then 
            grp_fu_141_p2 <= pre_grp_fu_141_p2;
        else 
            grp_fu_141_p2 <= pre_grp_fu_141_p2_reg;
        end if; 
    end process;


    grp_fu_145_p2_assign_proc : process(grp_fu_145_ce, pre_grp_fu_145_p2, pre_grp_fu_145_p2_reg)
    begin
        if ((grp_fu_145_ce = ap_const_logic_1)) then 
            grp_fu_145_p2 <= pre_grp_fu_145_p2;
        else 
            grp_fu_145_p2 <= pre_grp_fu_145_p2_reg;
        end if; 
    end process;


    grp_fu_149_p2_assign_proc : process(grp_fu_149_ce, pre_grp_fu_149_p2, pre_grp_fu_149_p2_reg)
    begin
        if ((grp_fu_149_ce = ap_const_logic_1)) then 
            grp_fu_149_p2 <= pre_grp_fu_149_p2;
        else 
            grp_fu_149_p2 <= pre_grp_fu_149_p2_reg;
        end if; 
    end process;


    grp_fu_153_p2_assign_proc : process(grp_fu_153_ce, pre_grp_fu_153_p2, pre_grp_fu_153_p2_reg)
    begin
        if ((grp_fu_153_ce = ap_const_logic_1)) then 
            grp_fu_153_p2 <= pre_grp_fu_153_p2;
        else 
            grp_fu_153_p2 <= pre_grp_fu_153_p2_reg;
        end if; 
    end process;


    grp_fu_157_p2_assign_proc : process(grp_fu_157_ce, pre_grp_fu_157_p2, pre_grp_fu_157_p2_reg)
    begin
        if ((grp_fu_157_ce = ap_const_logic_1)) then 
            grp_fu_157_p2 <= pre_grp_fu_157_p2;
        else 
            grp_fu_157_p2 <= pre_grp_fu_157_p2_reg;
        end if; 
    end process;


    grp_fu_161_p2_assign_proc : process(grp_fu_161_ce, pre_grp_fu_161_p2, pre_grp_fu_161_p2_reg)
    begin
        if ((grp_fu_161_ce = ap_const_logic_1)) then 
            grp_fu_161_p2 <= pre_grp_fu_161_p2;
        else 
            grp_fu_161_p2 <= pre_grp_fu_161_p2_reg;
        end if; 
    end process;


    grp_fu_165_p2_assign_proc : process(grp_fu_165_ce, pre_grp_fu_165_p2, pre_grp_fu_165_p2_reg)
    begin
        if ((grp_fu_165_ce = ap_const_logic_1)) then 
            grp_fu_165_p2 <= pre_grp_fu_165_p2;
        else 
            grp_fu_165_p2 <= pre_grp_fu_165_p2_reg;
        end if; 
    end process;

    i_cast_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),32));
    icmp_ln302_fu_193_p2 <= "1" when (signed(i_cast_fu_189_p1) < signed(nCols_assign_load)) else "0";
    or_ln313_i_fu_693_p9 <= (((((((bitcast_ln313_7_fu_689_p1 & bitcast_ln313_6_fu_685_p1) & bitcast_ln313_5_fu_681_p1) & bitcast_ln313_4_fu_677_p1) & bitcast_ln313_3_fu_673_p1) & bitcast_ln313_2_fu_669_p1) & bitcast_ln313_1_fu_665_p1) & bitcast_ln313_fu_661_p1);
    trunc_ln304_fu_219_p1 <= dualInfeasConstr_SVfifo_i_dout(64 - 1 downto 0);
    trunc_ln305_1_fu_339_p4 <= dualInfeasLbRay_SVfifo_i_dout(383 downto 320);
    trunc_ln305_2_fu_349_p4 <= dualInfeasLbRay_SVfifo_i_dout(447 downto 384);
    trunc_ln305_3_fu_359_p4 <= dualInfeasLbRay_SVfifo_i_dout(511 downto 448);
    trunc_ln305_7_fu_299_p4 <= dualInfeasLbRay_SVfifo_i_dout(127 downto 64);
    trunc_ln305_8_fu_309_p4 <= dualInfeasLbRay_SVfifo_i_dout(191 downto 128);
    trunc_ln305_9_fu_319_p4 <= dualInfeasLbRay_SVfifo_i_dout(255 downto 192);
    trunc_ln305_fu_295_p1 <= dualInfeasLbRay_SVfifo_i_dout(64 - 1 downto 0);
    trunc_ln305_s_fu_329_p4 <= dualInfeasLbRay_SVfifo_i_dout(319 downto 256);
    trunc_ln306_1_fu_447_p4 <= dualInfeasUbRay_SVfifo_i_dout(383 downto 320);
    trunc_ln306_2_fu_457_p4 <= dualInfeasUbRay_SVfifo_i_dout(447 downto 384);
    trunc_ln306_3_fu_467_p4 <= dualInfeasUbRay_SVfifo_i_dout(511 downto 448);
    trunc_ln306_7_fu_407_p4 <= dualInfeasUbRay_SVfifo_i_dout(127 downto 64);
    trunc_ln306_8_fu_417_p4 <= dualInfeasUbRay_SVfifo_i_dout(191 downto 128);
    trunc_ln306_9_fu_427_p4 <= dualInfeasUbRay_SVfifo_i_dout(255 downto 192);
    trunc_ln306_fu_403_p1 <= dualInfeasUbRay_SVfifo_i_dout(64 - 1 downto 0);
    trunc_ln306_s_fu_437_p4 <= dualInfeasUbRay_SVfifo_i_dout(319 downto 256);
end behav;
