// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Infeasi_Res_S2_Block_entry_split_split_split_split_split_split_split_split_split_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        dPrimalInfeasRes_dout,
        dPrimalInfeasRes_num_data_valid,
        dPrimalInfeasRes_fifo_cap,
        dPrimalInfeasRes_empty_n,
        dPrimalInfeasRes_read,
        dPrimalInfeasRes_val,
        dPrimalInfeasRes_val_ap_vld,
        dDualInfeasRes_dout,
        dDualInfeasRes_num_data_valid,
        dDualInfeasRes_fifo_cap,
        dDualInfeasRes_empty_n,
        dDualInfeasRes_read,
        dDualInfeasRes_val,
        dDualInfeasRes_val_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] dPrimalInfeasRes_dout;
input  [2:0] dPrimalInfeasRes_num_data_valid;
input  [2:0] dPrimalInfeasRes_fifo_cap;
input   dPrimalInfeasRes_empty_n;
output   dPrimalInfeasRes_read;
output  [63:0] dPrimalInfeasRes_val;
output   dPrimalInfeasRes_val_ap_vld;
input  [63:0] dDualInfeasRes_dout;
input  [2:0] dDualInfeasRes_num_data_valid;
input  [2:0] dDualInfeasRes_fifo_cap;
input   dDualInfeasRes_empty_n;
output   dDualInfeasRes_read;
output  [63:0] dDualInfeasRes_val;
output   dDualInfeasRes_val_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] dPrimalInfeasRes_val;
reg dPrimalInfeasRes_val_ap_vld;
reg[63:0] dDualInfeasRes_val;
reg dDualInfeasRes_val_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dPrimalInfeasRes_blk_n;
reg    dDualInfeasRes_blk_n;
reg    ap_block_state1;
reg    dPrimalInfeasRes_read_local;
reg   [63:0] dPrimalInfeasRes_val_preg;
reg    dDualInfeasRes_read_local;
reg   [63:0] dDualInfeasRes_val_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 dPrimalInfeasRes_val_preg = 64'd0;
#0 dDualInfeasRes_val_preg = 64'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        dDualInfeasRes_val_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            dDualInfeasRes_val_preg <= dDualInfeasRes_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        dPrimalInfeasRes_val_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            dPrimalInfeasRes_val_preg <= dPrimalInfeasRes_dout;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dDualInfeasRes_blk_n = dDualInfeasRes_empty_n;
    end else begin
        dDualInfeasRes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dDualInfeasRes_read_local = 1'b1;
    end else begin
        dDualInfeasRes_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dDualInfeasRes_val = dDualInfeasRes_dout;
    end else begin
        dDualInfeasRes_val = dDualInfeasRes_val_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dDualInfeasRes_val_ap_vld = 1'b1;
    end else begin
        dDualInfeasRes_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dPrimalInfeasRes_blk_n = dPrimalInfeasRes_empty_n;
    end else begin
        dPrimalInfeasRes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dPrimalInfeasRes_read_local = 1'b1;
    end else begin
        dPrimalInfeasRes_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dPrimalInfeasRes_val = dPrimalInfeasRes_dout;
    end else begin
        dPrimalInfeasRes_val = dPrimalInfeasRes_val_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dPrimalInfeasRes_val_ap_vld = 1'b1;
    end else begin
        dPrimalInfeasRes_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (dDualInfeasRes_empty_n == 1'b0) | (dPrimalInfeasRes_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign dDualInfeasRes_read = dDualInfeasRes_read_local;

assign dPrimalInfeasRes_read = dPrimalInfeasRes_read_local;

endmodule //Infeasi_Res_S2_Block_entry_split_split_split_split_split_split_split_split_split_proc1
