// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Infeasi_Res_S2_scale_and_twoNormSquared_noScaled (
        primalInfeasBound_fifo_dout,
        primalInfeasBound_fifo_empty_n,
        primalInfeasBound_fifo_read,
        pConstrResSq,
        n,
        ap_clk,
        ap_rst,
        primalInfeasBound_fifo_num_data_valid,
        primalInfeasBound_fifo_fifo_cap,
        n_ap_vld,
        pConstrResSq_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [511:0] primalInfeasBound_fifo_dout;
input   primalInfeasBound_fifo_empty_n;
output   primalInfeasBound_fifo_read;
output  [63:0] pConstrResSq;
input  [31:0] n;
input   ap_clk;
input   ap_rst;
input  [2:0] primalInfeasBound_fifo_num_data_valid;
input  [2:0] primalInfeasBound_fifo_fifo_cap;
input   n_ap_vld;
output   pConstrResSq_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    twoNormSquared_10_U0_ap_start;
wire    twoNormSquared_10_U0_ap_done;
wire    twoNormSquared_10_U0_ap_continue;
wire    twoNormSquared_10_U0_ap_idle;
wire    twoNormSquared_10_U0_ap_ready;
wire    twoNormSquared_10_U0_primalInfeasBound_fifo_read;
wire   [63:0] twoNormSquared_10_U0_res;
wire    twoNormSquared_10_U0_res_ap_vld;

Infeasi_Res_S2_twoNormSquared_10 twoNormSquared_10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(twoNormSquared_10_U0_ap_start),
    .ap_done(twoNormSquared_10_U0_ap_done),
    .ap_continue(twoNormSquared_10_U0_ap_continue),
    .ap_idle(twoNormSquared_10_U0_ap_idle),
    .ap_ready(twoNormSquared_10_U0_ap_ready),
    .primalInfeasBound_fifo_dout(primalInfeasBound_fifo_dout),
    .primalInfeasBound_fifo_num_data_valid(primalInfeasBound_fifo_num_data_valid),
    .primalInfeasBound_fifo_fifo_cap(primalInfeasBound_fifo_fifo_cap),
    .primalInfeasBound_fifo_empty_n(primalInfeasBound_fifo_empty_n),
    .primalInfeasBound_fifo_read(twoNormSquared_10_U0_primalInfeasBound_fifo_read),
    .n(n),
    .res(twoNormSquared_10_U0_res),
    .res_ap_vld(twoNormSquared_10_U0_res_ap_vld)
);

assign ap_done = twoNormSquared_10_U0_ap_done;

assign ap_idle = twoNormSquared_10_U0_ap_idle;

assign ap_ready = twoNormSquared_10_U0_ap_ready;

assign pConstrResSq = twoNormSquared_10_U0_res;

assign pConstrResSq_ap_vld = twoNormSquared_10_U0_res_ap_vld;

assign primalInfeasBound_fifo_read = twoNormSquared_10_U0_primalInfeasBound_fifo_read;

assign twoNormSquared_10_U0_ap_continue = ap_continue;

assign twoNormSquared_10_U0_ap_start = ap_start;

endmodule //Infeasi_Res_S2_scale_and_twoNormSquared_noScaled
