// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Infeasi_Res_S2_scale_and_twoNorm_noScaled (
        dualInfeasConstr_axpyfifo_dout,
        dualInfeasConstr_axpyfifo_empty_n,
        dualInfeasConstr_axpyfifo_read,
        dPrimalInfeasRes_din,
        dPrimalInfeasRes_full_n,
        dPrimalInfeasRes_write,
        n,
        ap_clk,
        ap_rst,
        n_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [511:0] dualInfeasConstr_axpyfifo_dout;
input   dualInfeasConstr_axpyfifo_empty_n;
output   dualInfeasConstr_axpyfifo_read;
output  [63:0] dPrimalInfeasRes_din;
input   dPrimalInfeasRes_full_n;
output   dPrimalInfeasRes_write;
input  [31:0] n;
input   ap_clk;
input   ap_rst;
input   n_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    twoNorm_U0_ap_start;
wire    twoNorm_U0_ap_done;
wire    twoNorm_U0_ap_continue;
wire    twoNorm_U0_ap_idle;
wire    twoNorm_U0_ap_ready;
wire    twoNorm_U0_dualInfeasConstr_axpyfifo_read;
wire   [63:0] twoNorm_U0_dPrimalInfeasRes_din;
wire    twoNorm_U0_dPrimalInfeasRes_write;

Infeasi_Res_S2_twoNorm twoNorm_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(twoNorm_U0_ap_start),
    .ap_done(twoNorm_U0_ap_done),
    .ap_continue(twoNorm_U0_ap_continue),
    .ap_idle(twoNorm_U0_ap_idle),
    .ap_ready(twoNorm_U0_ap_ready),
    .dualInfeasConstr_axpyfifo_dout(dualInfeasConstr_axpyfifo_dout),
    .dualInfeasConstr_axpyfifo_num_data_valid(3'd0),
    .dualInfeasConstr_axpyfifo_fifo_cap(3'd0),
    .dualInfeasConstr_axpyfifo_empty_n(dualInfeasConstr_axpyfifo_empty_n),
    .dualInfeasConstr_axpyfifo_read(twoNorm_U0_dualInfeasConstr_axpyfifo_read),
    .n(n),
    .dPrimalInfeasRes_din(twoNorm_U0_dPrimalInfeasRes_din),
    .dPrimalInfeasRes_num_data_valid(3'd0),
    .dPrimalInfeasRes_fifo_cap(3'd0),
    .dPrimalInfeasRes_full_n(dPrimalInfeasRes_full_n),
    .dPrimalInfeasRes_write(twoNorm_U0_dPrimalInfeasRes_write)
);

assign ap_done = twoNorm_U0_ap_done;

assign ap_idle = twoNorm_U0_ap_idle;

assign ap_ready = twoNorm_U0_ap_ready;

assign dPrimalInfeasRes_din = twoNorm_U0_dPrimalInfeasRes_din;

assign dPrimalInfeasRes_write = twoNorm_U0_dPrimalInfeasRes_write;

assign dualInfeasConstr_axpyfifo_read = twoNorm_U0_dualInfeasConstr_axpyfifo_read;

assign twoNorm_U0_ap_continue = ap_continue;

assign twoNorm_U0_ap_start = ap_start;

endmodule //Infeasi_Res_S2_scale_and_twoNorm_noScaled
