// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Infeasi_Res_S2_loadDDR_data_18 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem5_AWVALID,
        m_axi_gmem5_AWREADY,
        m_axi_gmem5_AWADDR,
        m_axi_gmem5_AWID,
        m_axi_gmem5_AWLEN,
        m_axi_gmem5_AWSIZE,
        m_axi_gmem5_AWBURST,
        m_axi_gmem5_AWLOCK,
        m_axi_gmem5_AWCACHE,
        m_axi_gmem5_AWPROT,
        m_axi_gmem5_AWQOS,
        m_axi_gmem5_AWREGION,
        m_axi_gmem5_AWUSER,
        m_axi_gmem5_WVALID,
        m_axi_gmem5_WREADY,
        m_axi_gmem5_WDATA,
        m_axi_gmem5_WSTRB,
        m_axi_gmem5_WLAST,
        m_axi_gmem5_WID,
        m_axi_gmem5_WUSER,
        m_axi_gmem5_ARVALID,
        m_axi_gmem5_ARREADY,
        m_axi_gmem5_ARADDR,
        m_axi_gmem5_ARID,
        m_axi_gmem5_ARLEN,
        m_axi_gmem5_ARSIZE,
        m_axi_gmem5_ARBURST,
        m_axi_gmem5_ARLOCK,
        m_axi_gmem5_ARCACHE,
        m_axi_gmem5_ARPROT,
        m_axi_gmem5_ARQOS,
        m_axi_gmem5_ARREGION,
        m_axi_gmem5_ARUSER,
        m_axi_gmem5_RVALID,
        m_axi_gmem5_RREADY,
        m_axi_gmem5_RDATA,
        m_axi_gmem5_RLAST,
        m_axi_gmem5_RID,
        m_axi_gmem5_RFIFONUM,
        m_axi_gmem5_RUSER,
        m_axi_gmem5_RRESP,
        m_axi_gmem5_BVALID,
        m_axi_gmem5_BREADY,
        m_axi_gmem5_BRESP,
        m_axi_gmem5_BID,
        m_axi_gmem5_BUSER,
        x,
        primalInfeasRay_fifo_i_din,
        primalInfeasRay_fifo_i_num_data_valid,
        primalInfeasRay_fifo_i_fifo_cap,
        primalInfeasRay_fifo_i_full_n,
        primalInfeasRay_fifo_i_write,
        p_read,
        nCols_assign_c_din,
        nCols_assign_c_num_data_valid,
        nCols_assign_c_fifo_cap,
        nCols_assign_c_full_n,
        nCols_assign_c_write
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem5_AWVALID;
input   m_axi_gmem5_AWREADY;
output  [63:0] m_axi_gmem5_AWADDR;
output  [0:0] m_axi_gmem5_AWID;
output  [31:0] m_axi_gmem5_AWLEN;
output  [2:0] m_axi_gmem5_AWSIZE;
output  [1:0] m_axi_gmem5_AWBURST;
output  [1:0] m_axi_gmem5_AWLOCK;
output  [3:0] m_axi_gmem5_AWCACHE;
output  [2:0] m_axi_gmem5_AWPROT;
output  [3:0] m_axi_gmem5_AWQOS;
output  [3:0] m_axi_gmem5_AWREGION;
output  [0:0] m_axi_gmem5_AWUSER;
output   m_axi_gmem5_WVALID;
input   m_axi_gmem5_WREADY;
output  [511:0] m_axi_gmem5_WDATA;
output  [63:0] m_axi_gmem5_WSTRB;
output   m_axi_gmem5_WLAST;
output  [0:0] m_axi_gmem5_WID;
output  [0:0] m_axi_gmem5_WUSER;
output   m_axi_gmem5_ARVALID;
input   m_axi_gmem5_ARREADY;
output  [63:0] m_axi_gmem5_ARADDR;
output  [0:0] m_axi_gmem5_ARID;
output  [31:0] m_axi_gmem5_ARLEN;
output  [2:0] m_axi_gmem5_ARSIZE;
output  [1:0] m_axi_gmem5_ARBURST;
output  [1:0] m_axi_gmem5_ARLOCK;
output  [3:0] m_axi_gmem5_ARCACHE;
output  [2:0] m_axi_gmem5_ARPROT;
output  [3:0] m_axi_gmem5_ARQOS;
output  [3:0] m_axi_gmem5_ARREGION;
output  [0:0] m_axi_gmem5_ARUSER;
input   m_axi_gmem5_RVALID;
output   m_axi_gmem5_RREADY;
input  [511:0] m_axi_gmem5_RDATA;
input   m_axi_gmem5_RLAST;
input  [0:0] m_axi_gmem5_RID;
input  [12:0] m_axi_gmem5_RFIFONUM;
input  [0:0] m_axi_gmem5_RUSER;
input  [1:0] m_axi_gmem5_RRESP;
input   m_axi_gmem5_BVALID;
output   m_axi_gmem5_BREADY;
input  [1:0] m_axi_gmem5_BRESP;
input  [0:0] m_axi_gmem5_BID;
input  [0:0] m_axi_gmem5_BUSER;
input  [63:0] x;
output  [511:0] primalInfeasRay_fifo_i_din;
input  [2:0] primalInfeasRay_fifo_i_num_data_valid;
input  [2:0] primalInfeasRay_fifo_i_fifo_cap;
input   primalInfeasRay_fifo_i_full_n;
output   primalInfeasRay_fifo_i_write;
input  [31:0] p_read;
output  [31:0] nCols_assign_c_din;
input  [2:0] nCols_assign_c_num_data_valid;
input  [2:0] nCols_assign_c_fifo_cap;
input   nCols_assign_c_full_n;
output   nCols_assign_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem5_ARVALID;
reg[63:0] m_axi_gmem5_ARADDR;
reg[0:0] m_axi_gmem5_ARID;
reg[31:0] m_axi_gmem5_ARLEN;
reg[2:0] m_axi_gmem5_ARSIZE;
reg[1:0] m_axi_gmem5_ARBURST;
reg[1:0] m_axi_gmem5_ARLOCK;
reg[3:0] m_axi_gmem5_ARCACHE;
reg[2:0] m_axi_gmem5_ARPROT;
reg[3:0] m_axi_gmem5_ARQOS;
reg[3:0] m_axi_gmem5_ARREGION;
reg[0:0] m_axi_gmem5_ARUSER;
reg m_axi_gmem5_RREADY;
reg primalInfeasRay_fifo_i_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem5_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    nCols_assign_c_blk_n;
reg    ap_block_state1;
wire   [30:0] empty_fu_110_p3;
reg   [30:0] empty_reg_148;
wire  signed [57:0] trunc_ln58_6_fu_118_p4;
reg   [57:0] trunc_ln58_6_reg_153;
wire   [63:0] zext_ln58_fu_139_p1;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_idle;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_ready;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWVALID;
wire   [63:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWADDR;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWID;
wire   [31:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWLEN;
wire   [2:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWSIZE;
wire   [1:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWBURST;
wire   [1:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWLOCK;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWCACHE;
wire   [2:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWPROT;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWQOS;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWREGION;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWUSER;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WVALID;
wire   [511:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WDATA;
wire   [63:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WSTRB;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WLAST;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WID;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WUSER;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARVALID;
wire   [63:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARADDR;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARID;
wire   [31:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLEN;
wire   [2:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARSIZE;
wire   [1:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARBURST;
wire   [1:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLOCK;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARCACHE;
wire   [2:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARPROT;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARQOS;
wire   [3:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARREGION;
wire   [0:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARUSER;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_RREADY;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_BREADY;
wire   [511:0] grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_din;
wire    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_write;
reg    grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire  signed [63:0] sext_ln58_fu_128_p1;
reg    nCols_assign_c_write_local;
wire   [0:0] icmp_ln58_fu_100_p2;
wire   [30:0] trunc_ln58_fu_106_p1;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 14'd1;
#0 grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg = 1'b0;
end

Infeasi_Res_S2_loadDDR_data_18_Pipeline_loadDDR_data grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start),
    .ap_done(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done),
    .ap_idle(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_idle),
    .ap_ready(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_ready),
    .m_axi_gmem5_AWVALID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWVALID),
    .m_axi_gmem5_AWREADY(1'b0),
    .m_axi_gmem5_AWADDR(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWADDR),
    .m_axi_gmem5_AWID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWID),
    .m_axi_gmem5_AWLEN(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWLEN),
    .m_axi_gmem5_AWSIZE(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWSIZE),
    .m_axi_gmem5_AWBURST(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWBURST),
    .m_axi_gmem5_AWLOCK(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWLOCK),
    .m_axi_gmem5_AWCACHE(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWCACHE),
    .m_axi_gmem5_AWPROT(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWPROT),
    .m_axi_gmem5_AWQOS(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWQOS),
    .m_axi_gmem5_AWREGION(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWREGION),
    .m_axi_gmem5_AWUSER(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_AWUSER),
    .m_axi_gmem5_WVALID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WVALID),
    .m_axi_gmem5_WREADY(1'b0),
    .m_axi_gmem5_WDATA(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WDATA),
    .m_axi_gmem5_WSTRB(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WSTRB),
    .m_axi_gmem5_WLAST(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WLAST),
    .m_axi_gmem5_WID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WID),
    .m_axi_gmem5_WUSER(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_WUSER),
    .m_axi_gmem5_ARVALID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARVALID),
    .m_axi_gmem5_ARREADY(m_axi_gmem5_ARREADY),
    .m_axi_gmem5_ARADDR(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARADDR),
    .m_axi_gmem5_ARID(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARID),
    .m_axi_gmem5_ARLEN(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLEN),
    .m_axi_gmem5_ARSIZE(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARSIZE),
    .m_axi_gmem5_ARBURST(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARBURST),
    .m_axi_gmem5_ARLOCK(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLOCK),
    .m_axi_gmem5_ARCACHE(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARCACHE),
    .m_axi_gmem5_ARPROT(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARPROT),
    .m_axi_gmem5_ARQOS(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARQOS),
    .m_axi_gmem5_ARREGION(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARREGION),
    .m_axi_gmem5_ARUSER(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARUSER),
    .m_axi_gmem5_RVALID(m_axi_gmem5_RVALID),
    .m_axi_gmem5_RREADY(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_RREADY),
    .m_axi_gmem5_RDATA(m_axi_gmem5_RDATA),
    .m_axi_gmem5_RLAST(m_axi_gmem5_RLAST),
    .m_axi_gmem5_RID(m_axi_gmem5_RID),
    .m_axi_gmem5_RFIFONUM(m_axi_gmem5_RFIFONUM),
    .m_axi_gmem5_RUSER(m_axi_gmem5_RUSER),
    .m_axi_gmem5_RRESP(m_axi_gmem5_RRESP),
    .m_axi_gmem5_BVALID(1'b0),
    .m_axi_gmem5_BREADY(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_BREADY),
    .m_axi_gmem5_BRESP(2'd0),
    .m_axi_gmem5_BID(1'd0),
    .m_axi_gmem5_BUSER(1'd0),
    .primalInfeasRay_fifo_i_din(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_din),
    .primalInfeasRay_fifo_i_num_data_valid(3'd0),
    .primalInfeasRay_fifo_i_fifo_cap(3'd0),
    .primalInfeasRay_fifo_i_full_n(primalInfeasRay_fifo_i_full_n),
    .primalInfeasRay_fifo_i_write(grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_write),
    .p_read(p_read),
    .sext_ln58(trunc_ln58_6_reg_153)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_ready == 1'b1)) begin
            grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_148 <= empty_fu_110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_gmem5_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_6_reg_153 <= {{x[63:6]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem5_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem5_blk_n_AR = m_axi_gmem5_ARREADY;
    end else begin
        gmem5_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmem5_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_ARADDR = sext_ln58_fu_128_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARADDR = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARADDR;
    end else begin
        m_axi_gmem5_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARBURST = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARBURST;
    end else begin
        m_axi_gmem5_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARCACHE = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARCACHE;
    end else begin
        m_axi_gmem5_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARID = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARID;
    end else begin
        m_axi_gmem5_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem5_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_ARLEN = zext_ln58_fu_139_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARLEN = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLEN;
    end else begin
        m_axi_gmem5_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARLOCK = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARLOCK;
    end else begin
        m_axi_gmem5_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARPROT = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARPROT;
    end else begin
        m_axi_gmem5_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARQOS = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARQOS;
    end else begin
        m_axi_gmem5_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARREGION = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARREGION;
    end else begin
        m_axi_gmem5_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARSIZE = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARSIZE;
    end else begin
        m_axi_gmem5_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARUSER = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARUSER;
    end else begin
        m_axi_gmem5_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem5_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem5_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_ARVALID = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_ARVALID;
    end else begin
        m_axi_gmem5_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem5_RREADY = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_m_axi_gmem5_RREADY;
    end else begin
        m_axi_gmem5_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        nCols_assign_c_blk_n = nCols_assign_c_full_n;
    end else begin
        nCols_assign_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        nCols_assign_c_write_local = 1'b1;
    end else begin
        nCols_assign_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        primalInfeasRay_fifo_i_write = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_write;
    end else begin
        primalInfeasRay_fifo_i_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem5_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (nCols_assign_c_full_n == 1'b0));
end

assign empty_fu_110_p3 = ((icmp_ln58_fu_100_p2[0:0] == 1'b1) ? trunc_ln58_fu_106_p1 : 31'd0);

assign grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_ap_start_reg;

assign icmp_ln58_fu_100_p2 = (($signed(p_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem5_AWADDR = 64'd0;

assign m_axi_gmem5_AWBURST = 2'd0;

assign m_axi_gmem5_AWCACHE = 4'd0;

assign m_axi_gmem5_AWID = 1'd0;

assign m_axi_gmem5_AWLEN = 32'd0;

assign m_axi_gmem5_AWLOCK = 2'd0;

assign m_axi_gmem5_AWPROT = 3'd0;

assign m_axi_gmem5_AWQOS = 4'd0;

assign m_axi_gmem5_AWREGION = 4'd0;

assign m_axi_gmem5_AWSIZE = 3'd0;

assign m_axi_gmem5_AWUSER = 1'd0;

assign m_axi_gmem5_AWVALID = 1'b0;

assign m_axi_gmem5_BREADY = 1'b0;

assign m_axi_gmem5_WDATA = 512'd0;

assign m_axi_gmem5_WID = 1'd0;

assign m_axi_gmem5_WLAST = 1'b0;

assign m_axi_gmem5_WSTRB = 64'd0;

assign m_axi_gmem5_WUSER = 1'd0;

assign m_axi_gmem5_WVALID = 1'b0;

assign nCols_assign_c_din = p_read;

assign nCols_assign_c_write = nCols_assign_c_write_local;

assign primalInfeasRay_fifo_i_din = grp_loadDDR_data_18_Pipeline_loadDDR_data_fu_84_primalInfeasRay_fifo_i_din;

assign sext_ln58_fu_128_p1 = trunc_ln58_6_fu_118_p4;

assign trunc_ln58_6_fu_118_p4 = {{x[63:6]}};

assign trunc_ln58_fu_106_p1 = p_read[30:0];

assign zext_ln58_fu_139_p1 = empty_reg_148;

endmodule //Infeasi_Res_S2_loadDDR_data_18
