-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pl_kernel_projlub_Pipeline_VITIS_LOOP_42_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    temp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    temp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    temp_empty_n : IN STD_LOGIC;
    temp_read : OUT STD_LOGIC;
    lb_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    lb_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    lb_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    lb_s_i_empty_n : IN STD_LOGIC;
    lb_s_i_read : OUT STD_LOGIC;
    ub_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    ub_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    ub_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    ub_s_i_empty_n : IN STD_LOGIC;
    ub_s_i_read : OUT STD_LOGIC;
    xupdate_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    xupdate_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    xupdate_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    xupdate_i_full_n : IN STD_LOGIC;
    xupdate_i_write : OUT STD_LOGIC;
    len : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of pl_kernel_projlub_Pipeline_VITIS_LOOP_42_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv30_1 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110100";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv32_F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln42_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal temp_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal lb_s_i_blk_n : STD_LOGIC;
    signal ub_s_i_blk_n : STD_LOGIC;
    signal xupdate_i_blk_n : STD_LOGIC;
    signal i_fu_92 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    signal add_ln42_fu_189_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (29 downto 0);
    signal temp_read_local : STD_LOGIC;
    signal lb_s_i_read_local : STD_LOGIC;
    signal ub_s_i_read_local : STD_LOGIC;
    signal or_ln54_1_fu_1201_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal xupdate_i_write_local : STD_LOGIC;
    signal bitcast_ln44_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln46_fu_355_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln51_fu_459_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln45_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln44_1_fu_248_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln46_1_fu_360_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln51_1_fu_660_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln45_1_fu_304_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln44_2_fu_253_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln46_2_fu_365_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln51_2_fu_867_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln45_2_fu_309_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln44_3_fu_258_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln46_3_fu_370_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln51_3_fu_1074_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln45_3_fu_314_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln40_fu_179_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln44_fu_209_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln44_3_fu_213_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln44_4_fu_223_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln44_5_fu_233_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln45_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln45_3_fu_269_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln45_4_fu_279_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln45_5_fu_289_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln46_fu_321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln46_3_fu_325_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln46_4_fu_335_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln46_5_fu_345_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_375_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_fu_385_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_1_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_389_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_1_fu_399_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_3_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_2_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_1_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_1_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln52_fu_468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_472_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_fu_482_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_1_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_486_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_1_fu_496_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_3_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_1_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_1_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_564_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_2_fu_574_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_5_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_4_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_584_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_3_fu_594_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_7_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_6_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_2_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_3_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_2_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_3_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln52_1_fu_669_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_673_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_2_fu_683_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_5_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_4_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_687_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_3_fu_697_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_7_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_6_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_2_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_3_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_2_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_3_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_771_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_4_fu_781_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_9_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_8_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_791_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_5_fu_801_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_11_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_10_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_4_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_5_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_4_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_5_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln52_2_fu_876_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_14_fu_880_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_4_fu_890_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_9_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_8_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_894_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_5_fu_904_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_11_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_10_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_4_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_5_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_4_fu_950_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_5_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_978_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_6_fu_988_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_13_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_12_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_998_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln51_7_fu_1008_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln51_15_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_14_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_6_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_7_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_6_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_7_fu_1068_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln52_3_fu_1083_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_20_fu_1087_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_6_fu_1097_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_13_fu_1127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_12_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_1101_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln52_7_fu_1111_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln52_15_fu_1145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_14_fu_1139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_6_fu_1133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_7_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_6_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_7_fu_1171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_556_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln52_1_fu_763_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln52_2_fu_970_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln52_3_fu_1177_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln54_3_fu_1197_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln54_2_fu_1193_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln54_1_fu_1189_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln54_fu_1185_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pl_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dcmp_64ns_64ns_1_1_no_dsp_1_U87 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => bitcast_ln44_fu_243_p1,
        din1 => bitcast_ln46_fu_355_p1,
        opcode => ap_const_lv5_2,
        dout => tmp_2_fu_127_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U88 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => select_ln51_fu_459_p3,
        din1 => bitcast_ln45_fu_299_p1,
        opcode => ap_const_lv5_4,
        dout => tmp_5_fu_131_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U89 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => bitcast_ln44_1_fu_248_p1,
        din1 => bitcast_ln46_1_fu_360_p1,
        opcode => ap_const_lv5_2,
        dout => tmp_8_fu_135_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U90 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => select_ln51_1_fu_660_p3,
        din1 => bitcast_ln45_1_fu_304_p1,
        opcode => ap_const_lv5_4,
        dout => tmp_10_fu_139_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U91 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => bitcast_ln44_2_fu_253_p1,
        din1 => bitcast_ln46_2_fu_365_p1,
        opcode => ap_const_lv5_2,
        dout => tmp_13_fu_143_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U92 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => select_ln51_2_fu_867_p3,
        din1 => bitcast_ln45_2_fu_309_p1,
        opcode => ap_const_lv5_4,
        dout => tmp_16_fu_147_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U93 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => bitcast_ln44_3_fu_258_p1,
        din1 => bitcast_ln46_3_fu_370_p1,
        opcode => ap_const_lv5_2,
        dout => tmp_19_fu_151_p2);

    dcmp_64ns_64ns_1_1_no_dsp_1_U94 : component pl_kernel_dcmp_64ns_64ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        din0 => select_ln51_3_fu_1074_p3,
        din1 => bitcast_ln45_3_fu_314_p1,
        opcode => ap_const_lv5_4,
        dout => tmp_22_fu_155_p2);

    flow_control_loop_pipe_sequential_init_U : component pl_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln42_fu_183_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_92 <= add_ln42_fu_189_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_92 <= ap_const_lv30_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln42_fu_189_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv30_1));
    and_ln51_1_fu_453_p2 <= (tmp_2_fu_127_p2 and and_ln51_fu_439_p2);
    and_ln51_2_fu_640_p2 <= (or_ln51_3_fu_634_p2 and or_ln51_2_fu_616_p2);
    and_ln51_3_fu_654_p2 <= (tmp_8_fu_135_p2 and and_ln51_2_fu_640_p2);
    and_ln51_4_fu_847_p2 <= (or_ln51_5_fu_841_p2 and or_ln51_4_fu_823_p2);
    and_ln51_5_fu_861_p2 <= (tmp_13_fu_143_p2 and and_ln51_4_fu_847_p2);
    and_ln51_6_fu_1054_p2 <= (or_ln51_7_fu_1048_p2 and or_ln51_6_fu_1030_p2);
    and_ln51_7_fu_1068_p2 <= (tmp_19_fu_151_p2 and and_ln51_6_fu_1054_p2);
    and_ln51_fu_439_p2 <= (or_ln51_fu_415_p2 and or_ln51_1_fu_433_p2);
    and_ln52_1_fu_550_p2 <= (tmp_5_fu_131_p2 and and_ln52_fu_536_p2);
    and_ln52_2_fu_743_p2 <= (or_ln52_3_fu_737_p2 and or_ln52_2_fu_719_p2);
    and_ln52_3_fu_757_p2 <= (tmp_10_fu_139_p2 and and_ln52_2_fu_743_p2);
    and_ln52_4_fu_950_p2 <= (or_ln52_5_fu_944_p2 and or_ln52_4_fu_926_p2);
    and_ln52_5_fu_964_p2 <= (tmp_16_fu_147_p2 and and_ln52_4_fu_950_p2);
    and_ln52_6_fu_1157_p2 <= (or_ln52_7_fu_1151_p2 and or_ln52_6_fu_1133_p2);
    and_ln52_7_fu_1171_p2 <= (tmp_22_fu_155_p2 and and_ln52_6_fu_1157_p2);
    and_ln52_fu_536_p2 <= (or_ln52_fu_512_p2 and or_ln52_1_fu_530_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_00001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_00001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(temp_empty_n, lb_s_i_empty_n, ub_s_i_empty_n, xupdate_i_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((xupdate_i_full_n = ap_const_logic_0) or (ub_s_i_empty_n = ap_const_logic_0) or (lb_s_i_empty_n = ap_const_logic_0) or (temp_empty_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln42_fu_183_p2)
    begin
        if (((icmp_ln42_fu_183_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_92, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv30_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_92;
        end if; 
    end process;

    bitcast_ln44_1_fu_248_p1 <= trunc_ln44_3_fu_213_p4;
    bitcast_ln44_2_fu_253_p1 <= trunc_ln44_4_fu_223_p4;
    bitcast_ln44_3_fu_258_p1 <= trunc_ln44_5_fu_233_p4;
    bitcast_ln44_fu_243_p1 <= trunc_ln44_fu_209_p1;
    bitcast_ln45_1_fu_304_p1 <= trunc_ln45_3_fu_269_p4;
    bitcast_ln45_2_fu_309_p1 <= trunc_ln45_4_fu_279_p4;
    bitcast_ln45_3_fu_314_p1 <= trunc_ln45_5_fu_289_p4;
    bitcast_ln45_fu_299_p1 <= trunc_ln45_fu_265_p1;
    bitcast_ln46_1_fu_360_p1 <= trunc_ln46_3_fu_325_p4;
    bitcast_ln46_2_fu_365_p1 <= trunc_ln46_4_fu_335_p4;
    bitcast_ln46_3_fu_370_p1 <= trunc_ln46_5_fu_345_p4;
    bitcast_ln46_fu_355_p1 <= trunc_ln46_fu_321_p1;
    bitcast_ln52_1_fu_669_p1 <= select_ln51_1_fu_660_p3;
    bitcast_ln52_2_fu_876_p1 <= select_ln51_2_fu_867_p3;
    bitcast_ln52_3_fu_1083_p1 <= select_ln51_3_fu_1074_p3;
    bitcast_ln52_fu_468_p1 <= select_ln51_fu_459_p3;
    bitcast_ln54_1_fu_1189_p1 <= select_ln52_1_fu_763_p3;
    bitcast_ln54_2_fu_1193_p1 <= select_ln52_2_fu_970_p3;
    bitcast_ln54_3_fu_1197_p1 <= select_ln52_3_fu_1177_p3;
    bitcast_ln54_fu_1185_p1 <= select_ln52_fu_556_p3;
    icmp_ln42_fu_183_p2 <= "1" when (signed(zext_ln40_fu_179_p1) < signed(len)) else "0";
    icmp_ln51_10_fu_829_p2 <= "0" when (tmp_12_fu_791_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_11_fu_835_p2 <= "1" when (trunc_ln51_5_fu_801_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_12_fu_1018_p2 <= "0" when (tmp_17_fu_978_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_13_fu_1024_p2 <= "1" when (trunc_ln51_6_fu_988_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_14_fu_1036_p2 <= "0" when (tmp_18_fu_998_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_15_fu_1042_p2 <= "1" when (trunc_ln51_7_fu_1008_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_1_fu_409_p2 <= "1" when (trunc_ln51_fu_385_p1 = ap_const_lv52_0) else "0";
    icmp_ln51_2_fu_421_p2 <= "0" when (tmp_1_fu_389_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_3_fu_427_p2 <= "1" when (trunc_ln51_1_fu_399_p1 = ap_const_lv52_0) else "0";
    icmp_ln51_4_fu_604_p2 <= "0" when (tmp_6_fu_564_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_5_fu_610_p2 <= "1" when (trunc_ln51_2_fu_574_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_6_fu_622_p2 <= "0" when (tmp_7_fu_584_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_7_fu_628_p2 <= "1" when (trunc_ln51_3_fu_594_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_8_fu_811_p2 <= "0" when (tmp_11_fu_771_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln51_9_fu_817_p2 <= "1" when (trunc_ln51_4_fu_781_p4 = ap_const_lv52_0) else "0";
    icmp_ln51_fu_403_p2 <= "0" when (tmp_fu_375_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_10_fu_932_p2 <= "0" when (tmp_15_fu_894_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_11_fu_938_p2 <= "1" when (trunc_ln52_5_fu_904_p4 = ap_const_lv52_0) else "0";
    icmp_ln52_12_fu_1121_p2 <= "0" when (tmp_20_fu_1087_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_13_fu_1127_p2 <= "1" when (trunc_ln52_6_fu_1097_p1 = ap_const_lv52_0) else "0";
    icmp_ln52_14_fu_1139_p2 <= "0" when (tmp_21_fu_1101_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_15_fu_1145_p2 <= "1" when (trunc_ln52_7_fu_1111_p4 = ap_const_lv52_0) else "0";
    icmp_ln52_1_fu_506_p2 <= "1" when (trunc_ln52_fu_482_p1 = ap_const_lv52_0) else "0";
    icmp_ln52_2_fu_518_p2 <= "0" when (tmp_4_fu_486_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_3_fu_524_p2 <= "1" when (trunc_ln52_1_fu_496_p1 = ap_const_lv52_0) else "0";
    icmp_ln52_4_fu_707_p2 <= "0" when (tmp_9_fu_673_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_5_fu_713_p2 <= "1" when (trunc_ln52_2_fu_683_p1 = ap_const_lv52_0) else "0";
    icmp_ln52_6_fu_725_p2 <= "0" when (tmp_s_fu_687_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_7_fu_731_p2 <= "1" when (trunc_ln52_3_fu_697_p4 = ap_const_lv52_0) else "0";
    icmp_ln52_8_fu_914_p2 <= "0" when (tmp_14_fu_880_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln52_9_fu_920_p2 <= "1" when (trunc_ln52_4_fu_890_p1 = ap_const_lv52_0) else "0";
    icmp_ln52_fu_500_p2 <= "0" when (tmp_3_fu_472_p4 = ap_const_lv11_7FF) else "1";

    lb_s_i_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, lb_s_i_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lb_s_i_blk_n <= lb_s_i_empty_n;
        else 
            lb_s_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lb_s_i_read <= lb_s_i_read_local;

    lb_s_i_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lb_s_i_read_local <= ap_const_logic_1;
        else 
            lb_s_i_read_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln51_1_fu_433_p2 <= (icmp_ln51_3_fu_427_p2 or icmp_ln51_2_fu_421_p2);
    or_ln51_2_fu_616_p2 <= (icmp_ln51_5_fu_610_p2 or icmp_ln51_4_fu_604_p2);
    or_ln51_3_fu_634_p2 <= (icmp_ln51_7_fu_628_p2 or icmp_ln51_6_fu_622_p2);
    or_ln51_4_fu_823_p2 <= (icmp_ln51_9_fu_817_p2 or icmp_ln51_8_fu_811_p2);
    or_ln51_5_fu_841_p2 <= (icmp_ln51_11_fu_835_p2 or icmp_ln51_10_fu_829_p2);
    or_ln51_6_fu_1030_p2 <= (icmp_ln51_13_fu_1024_p2 or icmp_ln51_12_fu_1018_p2);
    or_ln51_7_fu_1048_p2 <= (icmp_ln51_15_fu_1042_p2 or icmp_ln51_14_fu_1036_p2);
    or_ln51_fu_415_p2 <= (icmp_ln51_fu_403_p2 or icmp_ln51_1_fu_409_p2);
    or_ln52_1_fu_530_p2 <= (icmp_ln52_3_fu_524_p2 or icmp_ln52_2_fu_518_p2);
    or_ln52_2_fu_719_p2 <= (icmp_ln52_5_fu_713_p2 or icmp_ln52_4_fu_707_p2);
    or_ln52_3_fu_737_p2 <= (icmp_ln52_7_fu_731_p2 or icmp_ln52_6_fu_725_p2);
    or_ln52_4_fu_926_p2 <= (icmp_ln52_9_fu_920_p2 or icmp_ln52_8_fu_914_p2);
    or_ln52_5_fu_944_p2 <= (icmp_ln52_11_fu_938_p2 or icmp_ln52_10_fu_932_p2);
    or_ln52_6_fu_1133_p2 <= (icmp_ln52_13_fu_1127_p2 or icmp_ln52_12_fu_1121_p2);
    or_ln52_7_fu_1151_p2 <= (icmp_ln52_15_fu_1145_p2 or icmp_ln52_14_fu_1139_p2);
    or_ln52_fu_512_p2 <= (icmp_ln52_fu_500_p2 or icmp_ln52_1_fu_506_p2);
    or_ln54_1_fu_1201_p5 <= (((bitcast_ln54_3_fu_1197_p1 & bitcast_ln54_2_fu_1193_p1) & bitcast_ln54_1_fu_1189_p1) & bitcast_ln54_fu_1185_p1);
    select_ln51_1_fu_660_p3 <= 
        bitcast_ln46_1_fu_360_p1 when (and_ln51_3_fu_654_p2(0) = '1') else 
        bitcast_ln44_1_fu_248_p1;
    select_ln51_2_fu_867_p3 <= 
        bitcast_ln46_2_fu_365_p1 when (and_ln51_5_fu_861_p2(0) = '1') else 
        bitcast_ln44_2_fu_253_p1;
    select_ln51_3_fu_1074_p3 <= 
        bitcast_ln46_3_fu_370_p1 when (and_ln51_7_fu_1068_p2(0) = '1') else 
        bitcast_ln44_3_fu_258_p1;
    select_ln51_fu_459_p3 <= 
        bitcast_ln46_fu_355_p1 when (and_ln51_1_fu_453_p2(0) = '1') else 
        bitcast_ln44_fu_243_p1;
    select_ln52_1_fu_763_p3 <= 
        bitcast_ln45_1_fu_304_p1 when (and_ln52_3_fu_757_p2(0) = '1') else 
        select_ln51_1_fu_660_p3;
    select_ln52_2_fu_970_p3 <= 
        bitcast_ln45_2_fu_309_p1 when (and_ln52_5_fu_964_p2(0) = '1') else 
        select_ln51_2_fu_867_p3;
    select_ln52_3_fu_1177_p3 <= 
        bitcast_ln45_3_fu_314_p1 when (and_ln52_7_fu_1171_p2(0) = '1') else 
        select_ln51_3_fu_1074_p3;
    select_ln52_fu_556_p3 <= 
        bitcast_ln45_fu_299_p1 when (and_ln52_1_fu_550_p2(0) = '1') else 
        select_ln51_fu_459_p3;

    temp_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, temp_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_blk_n <= temp_empty_n;
        else 
            temp_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    temp_read <= temp_read_local;

    temp_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_read_local <= ap_const_logic_1;
        else 
            temp_read_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_11_fu_771_p4 <= temp_dout(190 downto 180);
    tmp_12_fu_791_p4 <= ub_s_i_dout(190 downto 180);
    tmp_14_fu_880_p4 <= bitcast_ln52_2_fu_876_p1(62 downto 52);
    tmp_15_fu_894_p4 <= lb_s_i_dout(190 downto 180);
    tmp_17_fu_978_p4 <= temp_dout(254 downto 244);
    tmp_18_fu_998_p4 <= ub_s_i_dout(254 downto 244);
    tmp_1_fu_389_p4 <= ub_s_i_dout(62 downto 52);
    tmp_20_fu_1087_p4 <= bitcast_ln52_3_fu_1083_p1(62 downto 52);
    tmp_21_fu_1101_p4 <= lb_s_i_dout(254 downto 244);
    tmp_3_fu_472_p4 <= bitcast_ln52_fu_468_p1(62 downto 52);
    tmp_4_fu_486_p4 <= lb_s_i_dout(62 downto 52);
    tmp_6_fu_564_p4 <= temp_dout(126 downto 116);
    tmp_7_fu_584_p4 <= ub_s_i_dout(126 downto 116);
    tmp_9_fu_673_p4 <= bitcast_ln52_1_fu_669_p1(62 downto 52);
    tmp_fu_375_p4 <= temp_dout(62 downto 52);
    tmp_s_fu_687_p4 <= lb_s_i_dout(126 downto 116);
    trunc_ln44_3_fu_213_p4 <= temp_dout(127 downto 64);
    trunc_ln44_4_fu_223_p4 <= temp_dout(191 downto 128);
    trunc_ln44_5_fu_233_p4 <= temp_dout(255 downto 192);
    trunc_ln44_fu_209_p1 <= temp_dout(64 - 1 downto 0);
    trunc_ln45_3_fu_269_p4 <= lb_s_i_dout(127 downto 64);
    trunc_ln45_4_fu_279_p4 <= lb_s_i_dout(191 downto 128);
    trunc_ln45_5_fu_289_p4 <= lb_s_i_dout(255 downto 192);
    trunc_ln45_fu_265_p1 <= lb_s_i_dout(64 - 1 downto 0);
    trunc_ln46_3_fu_325_p4 <= ub_s_i_dout(127 downto 64);
    trunc_ln46_4_fu_335_p4 <= ub_s_i_dout(191 downto 128);
    trunc_ln46_5_fu_345_p4 <= ub_s_i_dout(255 downto 192);
    trunc_ln46_fu_321_p1 <= ub_s_i_dout(64 - 1 downto 0);
    trunc_ln51_1_fu_399_p1 <= ub_s_i_dout(52 - 1 downto 0);
    trunc_ln51_2_fu_574_p4 <= temp_dout(115 downto 64);
    trunc_ln51_3_fu_594_p4 <= ub_s_i_dout(115 downto 64);
    trunc_ln51_4_fu_781_p4 <= temp_dout(179 downto 128);
    trunc_ln51_5_fu_801_p4 <= ub_s_i_dout(179 downto 128);
    trunc_ln51_6_fu_988_p4 <= temp_dout(243 downto 192);
    trunc_ln51_7_fu_1008_p4 <= ub_s_i_dout(243 downto 192);
    trunc_ln51_fu_385_p1 <= temp_dout(52 - 1 downto 0);
    trunc_ln52_1_fu_496_p1 <= lb_s_i_dout(52 - 1 downto 0);
    trunc_ln52_2_fu_683_p1 <= bitcast_ln52_1_fu_669_p1(52 - 1 downto 0);
    trunc_ln52_3_fu_697_p4 <= lb_s_i_dout(115 downto 64);
    trunc_ln52_4_fu_890_p1 <= bitcast_ln52_2_fu_876_p1(52 - 1 downto 0);
    trunc_ln52_5_fu_904_p4 <= lb_s_i_dout(179 downto 128);
    trunc_ln52_6_fu_1097_p1 <= bitcast_ln52_3_fu_1083_p1(52 - 1 downto 0);
    trunc_ln52_7_fu_1111_p4 <= lb_s_i_dout(243 downto 192);
    trunc_ln52_fu_482_p1 <= bitcast_ln52_fu_468_p1(52 - 1 downto 0);

    ub_s_i_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ub_s_i_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ub_s_i_blk_n <= ub_s_i_empty_n;
        else 
            ub_s_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ub_s_i_read <= ub_s_i_read_local;

    ub_s_i_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ub_s_i_read_local <= ap_const_logic_1;
        else 
            ub_s_i_read_local <= ap_const_logic_0;
        end if; 
    end process;


    xupdate_i_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xupdate_i_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xupdate_i_blk_n <= xupdate_i_full_n;
        else 
            xupdate_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xupdate_i_din <= or_ln54_1_fu_1201_p5;
    xupdate_i_write <= xupdate_i_write_local;

    xupdate_i_write_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xupdate_i_write_local <= ap_const_logic_1;
        else 
            xupdate_i_write_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln40_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),31));
end behav;
