-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pl_kernel_stage2 is
port (
    temp_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    temp_empty_n : IN STD_LOGIC;
    temp_read : OUT STD_LOGIC;
    m_axi_gmem4_AWVALID : OUT STD_LOGIC;
    m_axi_gmem4_AWREADY : IN STD_LOGIC;
    m_axi_gmem4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_WVALID : OUT STD_LOGIC;
    m_axi_gmem4_WREADY : IN STD_LOGIC;
    m_axi_gmem4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_WLAST : OUT STD_LOGIC;
    m_axi_gmem4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_ARVALID : OUT STD_LOGIC;
    m_axi_gmem4_ARREADY : IN STD_LOGIC;
    m_axi_gmem4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RVALID : IN STD_LOGIC;
    m_axi_gmem4_RREADY : OUT STD_LOGIC;
    m_axi_gmem4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem4_RLAST : IN STD_LOGIC;
    m_axi_gmem4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_BVALID : IN STD_LOGIC;
    m_axi_gmem4_BREADY : OUT STD_LOGIC;
    m_axi_gmem4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    lb : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_AWVALID : OUT STD_LOGIC;
    m_axi_gmem5_AWREADY : IN STD_LOGIC;
    m_axi_gmem5_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_WVALID : OUT STD_LOGIC;
    m_axi_gmem5_WREADY : IN STD_LOGIC;
    m_axi_gmem5_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem5_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_WLAST : OUT STD_LOGIC;
    m_axi_gmem5_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_ARVALID : OUT STD_LOGIC;
    m_axi_gmem5_ARREADY : IN STD_LOGIC;
    m_axi_gmem5_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem5_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem5_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem5_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem5_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RVALID : IN STD_LOGIC;
    m_axi_gmem5_RREADY : OUT STD_LOGIC;
    m_axi_gmem5_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem5_RLAST : IN STD_LOGIC;
    m_axi_gmem5_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem5_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_BVALID : IN STD_LOGIC;
    m_axi_gmem5_BREADY : OUT STD_LOGIC;
    m_axi_gmem5_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem5_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem5_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ub : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    xUpdate : IN STD_LOGIC_VECTOR (63 downto 0);
    len_assign_loc_dout : IN STD_LOGIC_VECTOR (30 downto 0);
    len_assign_loc_empty_n : IN STD_LOGIC;
    len_assign_loc_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    xUpdate_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    lb_ap_vld : IN STD_LOGIC;
    ub_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of pl_kernel_stage2 is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_xUpdate_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_xUpdate_c_write : STD_LOGIC;
    signal entry_proc_U0_len_assign_loc_read : STD_LOGIC;
    signal entry_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (30 downto 0);
    signal entry_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_channel_done_len_assign_loc_tmp1_channel : STD_LOGIC;
    signal len_assign_loc_tmp1_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_len_assign_loc_tmp1_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_len_assign_loc_tmp1_channel : STD_LOGIC;
    signal ap_channel_done_len_assign_loc_tmp_channel : STD_LOGIC;
    signal len_assign_loc_tmp_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_len_assign_loc_tmp_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_len_assign_loc_tmp_channel : STD_LOGIC;
    signal read_3_U0_ap_start : STD_LOGIC;
    signal read_3_U0_ap_done : STD_LOGIC;
    signal read_3_U0_ap_continue : STD_LOGIC;
    signal read_3_U0_ap_idle : STD_LOGIC;
    signal read_3_U0_ap_ready : STD_LOGIC;
    signal read_3_U0_start_out : STD_LOGIC;
    signal read_3_U0_start_write : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_AWVALID : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_3_U0_m_axi_gmem4_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_3_U0_m_axi_gmem4_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_3_U0_m_axi_gmem4_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_3_U0_m_axi_gmem4_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_3_U0_m_axi_gmem4_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_3_U0_m_axi_gmem4_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_WVALID : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_3_U0_m_axi_gmem4_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_3_U0_m_axi_gmem4_WLAST : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_ARVALID : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_3_U0_m_axi_gmem4_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_3_U0_m_axi_gmem4_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_3_U0_m_axi_gmem4_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_3_U0_m_axi_gmem4_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_3_U0_m_axi_gmem4_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_3_U0_m_axi_gmem4_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_3_U0_m_axi_gmem4_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_3_U0_m_axi_gmem4_RREADY : STD_LOGIC;
    signal read_3_U0_m_axi_gmem4_BREADY : STD_LOGIC;
    signal read_3_U0_lb_s_i_din : STD_LOGIC_VECTOR (255 downto 0);
    signal read_3_U0_lb_s_i_write : STD_LOGIC;
    signal read_3_U0_len_assign_loc_c1_din : STD_LOGIC_VECTOR (30 downto 0);
    signal read_3_U0_len_assign_loc_c1_write : STD_LOGIC;
    signal read_4_U0_ap_start : STD_LOGIC;
    signal read_4_U0_ap_done : STD_LOGIC;
    signal read_4_U0_ap_continue : STD_LOGIC;
    signal read_4_U0_ap_idle : STD_LOGIC;
    signal read_4_U0_ap_ready : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_AWVALID : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_4_U0_m_axi_gmem5_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_4_U0_m_axi_gmem5_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_4_U0_m_axi_gmem5_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_4_U0_m_axi_gmem5_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_4_U0_m_axi_gmem5_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_4_U0_m_axi_gmem5_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_WVALID : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_4_U0_m_axi_gmem5_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_4_U0_m_axi_gmem5_WLAST : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_ARVALID : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_4_U0_m_axi_gmem5_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_4_U0_m_axi_gmem5_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_4_U0_m_axi_gmem5_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_4_U0_m_axi_gmem5_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_4_U0_m_axi_gmem5_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_4_U0_m_axi_gmem5_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_4_U0_m_axi_gmem5_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_4_U0_m_axi_gmem5_RREADY : STD_LOGIC;
    signal read_4_U0_m_axi_gmem5_BREADY : STD_LOGIC;
    signal read_4_U0_ub_s_i_din : STD_LOGIC_VECTOR (255 downto 0);
    signal read_4_U0_ub_s_i_write : STD_LOGIC;
    signal projlub_U0_ap_start : STD_LOGIC;
    signal projlub_U0_ap_done : STD_LOGIC;
    signal projlub_U0_ap_continue : STD_LOGIC;
    signal projlub_U0_ap_idle : STD_LOGIC;
    signal projlub_U0_ap_ready : STD_LOGIC;
    signal projlub_U0_temp_read : STD_LOGIC;
    signal projlub_U0_lb_s_i_read : STD_LOGIC;
    signal projlub_U0_ub_s_i_read : STD_LOGIC;
    signal projlub_U0_xupdate_i_din : STD_LOGIC_VECTOR (255 downto 0);
    signal projlub_U0_xupdate_i_write : STD_LOGIC;
    signal projlub_U0_len_assign_loc_read : STD_LOGIC;
    signal projlub_U0_len_assign_loc_c_din : STD_LOGIC_VECTOR (30 downto 0);
    signal projlub_U0_len_assign_loc_c_write : STD_LOGIC;
    signal write_U0_ap_start : STD_LOGIC;
    signal write_U0_ap_done : STD_LOGIC;
    signal write_U0_ap_continue : STD_LOGIC;
    signal write_U0_ap_idle : STD_LOGIC;
    signal write_U0_ap_ready : STD_LOGIC;
    signal write_U0_xupdate_i_read : STD_LOGIC;
    signal write_U0_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal write_U0_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_U0_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_U0_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_U0_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_U0_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_U0_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_U0_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_WVALID : STD_LOGIC;
    signal write_U0_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal write_U0_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal write_U0_m_axi_gmem1_WLAST : STD_LOGIC;
    signal write_U0_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal write_U0_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_U0_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_U0_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_U0_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_U0_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_U0_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_U0_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_U0_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_U0_m_axi_gmem1_RREADY : STD_LOGIC;
    signal write_U0_m_axi_gmem1_BREADY : STD_LOGIC;
    signal write_U0_xUpdate_read : STD_LOGIC;
    signal write_U0_len_assign_loc_read : STD_LOGIC;
    signal xUpdate_c_full_n : STD_LOGIC;
    signal xUpdate_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal xUpdate_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal xUpdate_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal xUpdate_c_empty_n : STD_LOGIC;
    signal len_assign_loc_tmp_channel_dout : STD_LOGIC_VECTOR (30 downto 0);
    signal len_assign_loc_tmp_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_tmp_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_tmp_channel_empty_n : STD_LOGIC;
    signal len_assign_loc_tmp1_channel_dout : STD_LOGIC_VECTOR (30 downto 0);
    signal len_assign_loc_tmp1_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_tmp1_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_tmp1_channel_empty_n : STD_LOGIC;
    signal lb_s_i_full_n : STD_LOGIC;
    signal lb_s_i_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal lb_s_i_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal lb_s_i_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal lb_s_i_empty_n : STD_LOGIC;
    signal len_assign_loc_c1_full_n : STD_LOGIC;
    signal len_assign_loc_c1_dout : STD_LOGIC_VECTOR (30 downto 0);
    signal len_assign_loc_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_c1_empty_n : STD_LOGIC;
    signal ub_s_i_full_n : STD_LOGIC;
    signal ub_s_i_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal ub_s_i_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal ub_s_i_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal ub_s_i_empty_n : STD_LOGIC;
    signal xupdate_i_full_n : STD_LOGIC;
    signal xupdate_i_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal xupdate_i_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal xupdate_i_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal xupdate_i_empty_n : STD_LOGIC;
    signal len_assign_loc_c_full_n : STD_LOGIC;
    signal len_assign_loc_c_dout : STD_LOGIC_VECTOR (30 downto 0);
    signal len_assign_loc_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal len_assign_loc_c_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_3_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_4_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_4_U0_ap_ready : STD_LOGIC;
    signal start_for_write_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_U0_full_n : STD_LOGIC;
    signal start_for_write_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_U0_empty_n : STD_LOGIC;
    signal start_for_projlub_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_projlub_U0_full_n : STD_LOGIC;
    signal start_for_projlub_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_projlub_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pl_kernel_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        xUpdate : IN STD_LOGIC_VECTOR (63 downto 0);
        xUpdate_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        xUpdate_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xUpdate_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        xUpdate_c_full_n : IN STD_LOGIC;
        xUpdate_c_write : OUT STD_LOGIC;
        len_assign_loc_dout : IN STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_empty_n : IN STD_LOGIC;
        len_assign_loc_read : OUT STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (30 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component pl_kernel_read_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem4_AWVALID : OUT STD_LOGIC;
        m_axi_gmem4_AWREADY : IN STD_LOGIC;
        m_axi_gmem4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_WVALID : OUT STD_LOGIC;
        m_axi_gmem4_WREADY : IN STD_LOGIC;
        m_axi_gmem4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_WLAST : OUT STD_LOGIC;
        m_axi_gmem4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_ARVALID : OUT STD_LOGIC;
        m_axi_gmem4_ARREADY : IN STD_LOGIC;
        m_axi_gmem4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RVALID : IN STD_LOGIC;
        m_axi_gmem4_RREADY : OUT STD_LOGIC;
        m_axi_gmem4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem4_RLAST : IN STD_LOGIC;
        m_axi_gmem4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_BVALID : IN STD_LOGIC;
        m_axi_gmem4_BREADY : OUT STD_LOGIC;
        m_axi_gmem4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        lb : IN STD_LOGIC_VECTOR (63 downto 0);
        lb_s_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        lb_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_full_n : IN STD_LOGIC;
        lb_s_i_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_c1_din : OUT STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_c1_full_n : IN STD_LOGIC;
        len_assign_loc_c1_write : OUT STD_LOGIC );
    end component;


    component pl_kernel_read_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem5_AWVALID : OUT STD_LOGIC;
        m_axi_gmem5_AWREADY : IN STD_LOGIC;
        m_axi_gmem5_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_WVALID : OUT STD_LOGIC;
        m_axi_gmem5_WREADY : IN STD_LOGIC;
        m_axi_gmem5_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem5_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_WLAST : OUT STD_LOGIC;
        m_axi_gmem5_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_ARVALID : OUT STD_LOGIC;
        m_axi_gmem5_ARREADY : IN STD_LOGIC;
        m_axi_gmem5_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem5_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem5_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem5_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem5_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RVALID : IN STD_LOGIC;
        m_axi_gmem5_RREADY : OUT STD_LOGIC;
        m_axi_gmem5_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem5_RLAST : IN STD_LOGIC;
        m_axi_gmem5_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem5_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_BVALID : IN STD_LOGIC;
        m_axi_gmem5_BREADY : OUT STD_LOGIC;
        m_axi_gmem5_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem5_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem5_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ub_s_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        ub_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_full_n : IN STD_LOGIC;
        ub_s_i_write : OUT STD_LOGIC;
        ub : IN STD_LOGIC_VECTOR (63 downto 0);
        p_read : IN STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component pl_kernel_projlub IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        temp_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        temp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        temp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        temp_empty_n : IN STD_LOGIC;
        temp_read : OUT STD_LOGIC;
        lb_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        lb_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_empty_n : IN STD_LOGIC;
        lb_s_i_read : OUT STD_LOGIC;
        ub_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        ub_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_empty_n : IN STD_LOGIC;
        ub_s_i_read : OUT STD_LOGIC;
        xupdate_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        xupdate_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_full_n : IN STD_LOGIC;
        xupdate_i_write : OUT STD_LOGIC;
        len_assign_loc_dout : IN STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_empty_n : IN STD_LOGIC;
        len_assign_loc_read : OUT STD_LOGIC;
        len_assign_loc_c_din : OUT STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_c_full_n : IN STD_LOGIC;
        len_assign_loc_c_write : OUT STD_LOGIC );
    end component;


    component pl_kernel_write_r IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        xupdate_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        xupdate_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_empty_n : IN STD_LOGIC;
        xupdate_i_read : OUT STD_LOGIC;
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        xUpdate_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        xUpdate_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xUpdate_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        xUpdate_empty_n : IN STD_LOGIC;
        xUpdate_read : OUT STD_LOGIC;
        len_assign_loc_dout : IN STD_LOGIC_VECTOR (30 downto 0);
        len_assign_loc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        len_assign_loc_empty_n : IN STD_LOGIC;
        len_assign_loc_read : OUT STD_LOGIC );
    end component;


    component pl_kernel_fifo_w64_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pl_kernel_fifo_w31_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (30 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (30 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pl_kernel_fifo_w256_d64_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pl_kernel_start_for_write_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pl_kernel_start_for_projlub_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc_U0 : component pl_kernel_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_write_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        xUpdate => xUpdate,
        xUpdate_c_din => entry_proc_U0_xUpdate_c_din,
        xUpdate_c_num_data_valid => xUpdate_c_num_data_valid,
        xUpdate_c_fifo_cap => xUpdate_c_fifo_cap,
        xUpdate_c_full_n => xUpdate_c_full_n,
        xUpdate_c_write => entry_proc_U0_xUpdate_c_write,
        len_assign_loc_dout => len_assign_loc_dout,
        len_assign_loc_num_data_valid => ap_const_lv3_0,
        len_assign_loc_fifo_cap => ap_const_lv3_0,
        len_assign_loc_empty_n => len_assign_loc_empty_n,
        len_assign_loc_read => entry_proc_U0_len_assign_loc_read,
        ap_return_0 => entry_proc_U0_ap_return_0,
        ap_return_1 => entry_proc_U0_ap_return_1);

    read_3_U0 : component pl_kernel_read_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_3_U0_ap_start,
        start_full_n => start_for_projlub_U0_full_n,
        ap_done => read_3_U0_ap_done,
        ap_continue => read_3_U0_ap_continue,
        ap_idle => read_3_U0_ap_idle,
        ap_ready => read_3_U0_ap_ready,
        start_out => read_3_U0_start_out,
        start_write => read_3_U0_start_write,
        m_axi_gmem4_AWVALID => read_3_U0_m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY => ap_const_logic_0,
        m_axi_gmem4_AWADDR => read_3_U0_m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID => read_3_U0_m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN => read_3_U0_m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE => read_3_U0_m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST => read_3_U0_m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK => read_3_U0_m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE => read_3_U0_m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT => read_3_U0_m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS => read_3_U0_m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION => read_3_U0_m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER => read_3_U0_m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID => read_3_U0_m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY => ap_const_logic_0,
        m_axi_gmem4_WDATA => read_3_U0_m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB => read_3_U0_m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST => read_3_U0_m_axi_gmem4_WLAST,
        m_axi_gmem4_WID => read_3_U0_m_axi_gmem4_WID,
        m_axi_gmem4_WUSER => read_3_U0_m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID => read_3_U0_m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY => m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR => read_3_U0_m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID => read_3_U0_m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN => read_3_U0_m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE => read_3_U0_m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST => read_3_U0_m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK => read_3_U0_m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE => read_3_U0_m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT => read_3_U0_m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS => read_3_U0_m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION => read_3_U0_m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER => read_3_U0_m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID => m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY => read_3_U0_m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA => m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST => m_axi_gmem4_RLAST,
        m_axi_gmem4_RID => m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM => m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER => m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP => m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID => ap_const_logic_0,
        m_axi_gmem4_BREADY => read_3_U0_m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP => ap_const_lv2_0,
        m_axi_gmem4_BID => ap_const_lv1_0,
        m_axi_gmem4_BUSER => ap_const_lv1_0,
        lb => lb,
        lb_s_i_din => read_3_U0_lb_s_i_din,
        lb_s_i_num_data_valid => lb_s_i_num_data_valid,
        lb_s_i_fifo_cap => lb_s_i_fifo_cap,
        lb_s_i_full_n => lb_s_i_full_n,
        lb_s_i_write => read_3_U0_lb_s_i_write,
        p_read => len_assign_loc_tmp_channel_dout,
        len_assign_loc_c1_din => read_3_U0_len_assign_loc_c1_din,
        len_assign_loc_c1_num_data_valid => len_assign_loc_c1_num_data_valid,
        len_assign_loc_c1_fifo_cap => len_assign_loc_c1_fifo_cap,
        len_assign_loc_c1_full_n => len_assign_loc_c1_full_n,
        len_assign_loc_c1_write => read_3_U0_len_assign_loc_c1_write);

    read_4_U0 : component pl_kernel_read_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_4_U0_ap_start,
        ap_done => read_4_U0_ap_done,
        ap_continue => read_4_U0_ap_continue,
        ap_idle => read_4_U0_ap_idle,
        ap_ready => read_4_U0_ap_ready,
        m_axi_gmem5_AWVALID => read_4_U0_m_axi_gmem5_AWVALID,
        m_axi_gmem5_AWREADY => ap_const_logic_0,
        m_axi_gmem5_AWADDR => read_4_U0_m_axi_gmem5_AWADDR,
        m_axi_gmem5_AWID => read_4_U0_m_axi_gmem5_AWID,
        m_axi_gmem5_AWLEN => read_4_U0_m_axi_gmem5_AWLEN,
        m_axi_gmem5_AWSIZE => read_4_U0_m_axi_gmem5_AWSIZE,
        m_axi_gmem5_AWBURST => read_4_U0_m_axi_gmem5_AWBURST,
        m_axi_gmem5_AWLOCK => read_4_U0_m_axi_gmem5_AWLOCK,
        m_axi_gmem5_AWCACHE => read_4_U0_m_axi_gmem5_AWCACHE,
        m_axi_gmem5_AWPROT => read_4_U0_m_axi_gmem5_AWPROT,
        m_axi_gmem5_AWQOS => read_4_U0_m_axi_gmem5_AWQOS,
        m_axi_gmem5_AWREGION => read_4_U0_m_axi_gmem5_AWREGION,
        m_axi_gmem5_AWUSER => read_4_U0_m_axi_gmem5_AWUSER,
        m_axi_gmem5_WVALID => read_4_U0_m_axi_gmem5_WVALID,
        m_axi_gmem5_WREADY => ap_const_logic_0,
        m_axi_gmem5_WDATA => read_4_U0_m_axi_gmem5_WDATA,
        m_axi_gmem5_WSTRB => read_4_U0_m_axi_gmem5_WSTRB,
        m_axi_gmem5_WLAST => read_4_U0_m_axi_gmem5_WLAST,
        m_axi_gmem5_WID => read_4_U0_m_axi_gmem5_WID,
        m_axi_gmem5_WUSER => read_4_U0_m_axi_gmem5_WUSER,
        m_axi_gmem5_ARVALID => read_4_U0_m_axi_gmem5_ARVALID,
        m_axi_gmem5_ARREADY => m_axi_gmem5_ARREADY,
        m_axi_gmem5_ARADDR => read_4_U0_m_axi_gmem5_ARADDR,
        m_axi_gmem5_ARID => read_4_U0_m_axi_gmem5_ARID,
        m_axi_gmem5_ARLEN => read_4_U0_m_axi_gmem5_ARLEN,
        m_axi_gmem5_ARSIZE => read_4_U0_m_axi_gmem5_ARSIZE,
        m_axi_gmem5_ARBURST => read_4_U0_m_axi_gmem5_ARBURST,
        m_axi_gmem5_ARLOCK => read_4_U0_m_axi_gmem5_ARLOCK,
        m_axi_gmem5_ARCACHE => read_4_U0_m_axi_gmem5_ARCACHE,
        m_axi_gmem5_ARPROT => read_4_U0_m_axi_gmem5_ARPROT,
        m_axi_gmem5_ARQOS => read_4_U0_m_axi_gmem5_ARQOS,
        m_axi_gmem5_ARREGION => read_4_U0_m_axi_gmem5_ARREGION,
        m_axi_gmem5_ARUSER => read_4_U0_m_axi_gmem5_ARUSER,
        m_axi_gmem5_RVALID => m_axi_gmem5_RVALID,
        m_axi_gmem5_RREADY => read_4_U0_m_axi_gmem5_RREADY,
        m_axi_gmem5_RDATA => m_axi_gmem5_RDATA,
        m_axi_gmem5_RLAST => m_axi_gmem5_RLAST,
        m_axi_gmem5_RID => m_axi_gmem5_RID,
        m_axi_gmem5_RFIFONUM => m_axi_gmem5_RFIFONUM,
        m_axi_gmem5_RUSER => m_axi_gmem5_RUSER,
        m_axi_gmem5_RRESP => m_axi_gmem5_RRESP,
        m_axi_gmem5_BVALID => ap_const_logic_0,
        m_axi_gmem5_BREADY => read_4_U0_m_axi_gmem5_BREADY,
        m_axi_gmem5_BRESP => ap_const_lv2_0,
        m_axi_gmem5_BID => ap_const_lv1_0,
        m_axi_gmem5_BUSER => ap_const_lv1_0,
        ub_s_i_din => read_4_U0_ub_s_i_din,
        ub_s_i_num_data_valid => ub_s_i_num_data_valid,
        ub_s_i_fifo_cap => ub_s_i_fifo_cap,
        ub_s_i_full_n => ub_s_i_full_n,
        ub_s_i_write => read_4_U0_ub_s_i_write,
        ub => ub,
        p_read => len_assign_loc_tmp1_channel_dout);

    projlub_U0 : component pl_kernel_projlub
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => projlub_U0_ap_start,
        ap_done => projlub_U0_ap_done,
        ap_continue => projlub_U0_ap_continue,
        ap_idle => projlub_U0_ap_idle,
        ap_ready => projlub_U0_ap_ready,
        temp_dout => temp_dout,
        temp_num_data_valid => ap_const_lv7_0,
        temp_fifo_cap => ap_const_lv7_0,
        temp_empty_n => temp_empty_n,
        temp_read => projlub_U0_temp_read,
        lb_s_i_dout => lb_s_i_dout,
        lb_s_i_num_data_valid => lb_s_i_num_data_valid,
        lb_s_i_fifo_cap => lb_s_i_fifo_cap,
        lb_s_i_empty_n => lb_s_i_empty_n,
        lb_s_i_read => projlub_U0_lb_s_i_read,
        ub_s_i_dout => ub_s_i_dout,
        ub_s_i_num_data_valid => ub_s_i_num_data_valid,
        ub_s_i_fifo_cap => ub_s_i_fifo_cap,
        ub_s_i_empty_n => ub_s_i_empty_n,
        ub_s_i_read => projlub_U0_ub_s_i_read,
        xupdate_i_din => projlub_U0_xupdate_i_din,
        xupdate_i_num_data_valid => xupdate_i_num_data_valid,
        xupdate_i_fifo_cap => xupdate_i_fifo_cap,
        xupdate_i_full_n => xupdate_i_full_n,
        xupdate_i_write => projlub_U0_xupdate_i_write,
        len_assign_loc_dout => len_assign_loc_c1_dout,
        len_assign_loc_num_data_valid => len_assign_loc_c1_num_data_valid,
        len_assign_loc_fifo_cap => len_assign_loc_c1_fifo_cap,
        len_assign_loc_empty_n => len_assign_loc_c1_empty_n,
        len_assign_loc_read => projlub_U0_len_assign_loc_read,
        len_assign_loc_c_din => projlub_U0_len_assign_loc_c_din,
        len_assign_loc_c_num_data_valid => len_assign_loc_c_num_data_valid,
        len_assign_loc_c_fifo_cap => len_assign_loc_c_fifo_cap,
        len_assign_loc_c_full_n => len_assign_loc_c_full_n,
        len_assign_loc_c_write => projlub_U0_len_assign_loc_c_write);

    write_U0 : component pl_kernel_write_r
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => write_U0_ap_start,
        ap_done => write_U0_ap_done,
        ap_continue => write_U0_ap_continue,
        ap_idle => write_U0_ap_idle,
        ap_ready => write_U0_ap_ready,
        xupdate_i_dout => xupdate_i_dout,
        xupdate_i_num_data_valid => xupdate_i_num_data_valid,
        xupdate_i_fifo_cap => xupdate_i_fifo_cap,
        xupdate_i_empty_n => xupdate_i_empty_n,
        xupdate_i_read => write_U0_xupdate_i_read,
        m_axi_gmem1_AWVALID => write_U0_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR => write_U0_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => write_U0_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => write_U0_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => write_U0_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => write_U0_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => write_U0_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => write_U0_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => write_U0_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => write_U0_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => write_U0_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => write_U0_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => write_U0_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA => write_U0_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => write_U0_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => write_U0_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => write_U0_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => write_U0_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => write_U0_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => ap_const_logic_0,
        m_axi_gmem1_ARADDR => write_U0_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => write_U0_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => write_U0_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => write_U0_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => write_U0_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => write_U0_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => write_U0_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => write_U0_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => write_U0_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => write_U0_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => write_U0_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => ap_const_logic_0,
        m_axi_gmem1_RREADY => write_U0_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => ap_const_lv256_lc_1,
        m_axi_gmem1_RLAST => ap_const_logic_0,
        m_axi_gmem1_RID => ap_const_lv1_0,
        m_axi_gmem1_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem1_RUSER => ap_const_lv1_0,
        m_axi_gmem1_RRESP => ap_const_lv2_0,
        m_axi_gmem1_BVALID => m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY => write_U0_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => m_axi_gmem1_BRESP,
        m_axi_gmem1_BID => m_axi_gmem1_BID,
        m_axi_gmem1_BUSER => m_axi_gmem1_BUSER,
        xUpdate_dout => xUpdate_c_dout,
        xUpdate_num_data_valid => xUpdate_c_num_data_valid,
        xUpdate_fifo_cap => xUpdate_c_fifo_cap,
        xUpdate_empty_n => xUpdate_c_empty_n,
        xUpdate_read => write_U0_xUpdate_read,
        len_assign_loc_dout => len_assign_loc_c_dout,
        len_assign_loc_num_data_valid => len_assign_loc_c_num_data_valid,
        len_assign_loc_fifo_cap => len_assign_loc_c_fifo_cap,
        len_assign_loc_empty_n => len_assign_loc_c_empty_n,
        len_assign_loc_read => write_U0_len_assign_loc_read);

    xUpdate_c_U : component pl_kernel_fifo_w64_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_xUpdate_c_din,
        if_full_n => xUpdate_c_full_n,
        if_write => entry_proc_U0_xUpdate_c_write,
        if_dout => xUpdate_c_dout,
        if_num_data_valid => xUpdate_c_num_data_valid,
        if_fifo_cap => xUpdate_c_fifo_cap,
        if_empty_n => xUpdate_c_empty_n,
        if_read => write_U0_xUpdate_read);

    len_assign_loc_tmp_channel_U : component pl_kernel_fifo_w31_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ap_return_0,
        if_full_n => len_assign_loc_tmp_channel_full_n,
        if_write => ap_channel_done_len_assign_loc_tmp_channel,
        if_dout => len_assign_loc_tmp_channel_dout,
        if_num_data_valid => len_assign_loc_tmp_channel_num_data_valid,
        if_fifo_cap => len_assign_loc_tmp_channel_fifo_cap,
        if_empty_n => len_assign_loc_tmp_channel_empty_n,
        if_read => read_3_U0_ap_ready);

    len_assign_loc_tmp1_channel_U : component pl_kernel_fifo_w31_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ap_return_1,
        if_full_n => len_assign_loc_tmp1_channel_full_n,
        if_write => ap_channel_done_len_assign_loc_tmp1_channel,
        if_dout => len_assign_loc_tmp1_channel_dout,
        if_num_data_valid => len_assign_loc_tmp1_channel_num_data_valid,
        if_fifo_cap => len_assign_loc_tmp1_channel_fifo_cap,
        if_empty_n => len_assign_loc_tmp1_channel_empty_n,
        if_read => read_4_U0_ap_ready);

    lb_s_i_U : component pl_kernel_fifo_w256_d64_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_3_U0_lb_s_i_din,
        if_full_n => lb_s_i_full_n,
        if_write => read_3_U0_lb_s_i_write,
        if_dout => lb_s_i_dout,
        if_num_data_valid => lb_s_i_num_data_valid,
        if_fifo_cap => lb_s_i_fifo_cap,
        if_empty_n => lb_s_i_empty_n,
        if_read => projlub_U0_lb_s_i_read);

    len_assign_loc_c1_U : component pl_kernel_fifo_w31_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_3_U0_len_assign_loc_c1_din,
        if_full_n => len_assign_loc_c1_full_n,
        if_write => read_3_U0_len_assign_loc_c1_write,
        if_dout => len_assign_loc_c1_dout,
        if_num_data_valid => len_assign_loc_c1_num_data_valid,
        if_fifo_cap => len_assign_loc_c1_fifo_cap,
        if_empty_n => len_assign_loc_c1_empty_n,
        if_read => projlub_U0_len_assign_loc_read);

    ub_s_i_U : component pl_kernel_fifo_w256_d64_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_4_U0_ub_s_i_din,
        if_full_n => ub_s_i_full_n,
        if_write => read_4_U0_ub_s_i_write,
        if_dout => ub_s_i_dout,
        if_num_data_valid => ub_s_i_num_data_valid,
        if_fifo_cap => ub_s_i_fifo_cap,
        if_empty_n => ub_s_i_empty_n,
        if_read => projlub_U0_ub_s_i_read);

    xupdate_i_U : component pl_kernel_fifo_w256_d64_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => projlub_U0_xupdate_i_din,
        if_full_n => xupdate_i_full_n,
        if_write => projlub_U0_xupdate_i_write,
        if_dout => xupdate_i_dout,
        if_num_data_valid => xupdate_i_num_data_valid,
        if_fifo_cap => xupdate_i_fifo_cap,
        if_empty_n => xupdate_i_empty_n,
        if_read => write_U0_xupdate_i_read);

    len_assign_loc_c_U : component pl_kernel_fifo_w31_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => projlub_U0_len_assign_loc_c_din,
        if_full_n => len_assign_loc_c_full_n,
        if_write => projlub_U0_len_assign_loc_c_write,
        if_dout => len_assign_loc_c_dout,
        if_num_data_valid => len_assign_loc_c_num_data_valid,
        if_fifo_cap => len_assign_loc_c_fifo_cap,
        if_empty_n => len_assign_loc_c_empty_n,
        if_read => write_U0_len_assign_loc_read);

    start_for_write_U0_U : component pl_kernel_start_for_write_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_write_U0_din,
        if_full_n => start_for_write_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_write_U0_dout,
        if_empty_n => start_for_write_U0_empty_n,
        if_read => write_U0_ap_ready);

    start_for_projlub_U0_U : component pl_kernel_start_for_projlub_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_projlub_U0_din,
        if_full_n => start_for_projlub_U0_full_n,
        if_write => read_3_U0_start_write,
        if_dout => start_for_projlub_U0_dout,
        if_empty_n => start_for_projlub_U0_empty_n,
        if_read => projlub_U0_ap_ready);





    ap_sync_reg_channel_write_len_assign_loc_tmp1_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_len_assign_loc_tmp1_channel <= ap_const_logic_0;
            else
                if (((entry_proc_U0_ap_done and entry_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_len_assign_loc_tmp1_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_len_assign_loc_tmp1_channel <= ap_sync_channel_write_len_assign_loc_tmp1_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_len_assign_loc_tmp_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_len_assign_loc_tmp_channel <= ap_const_logic_0;
            else
                if (((entry_proc_U0_ap_done and entry_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_len_assign_loc_tmp_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_len_assign_loc_tmp_channel <= ap_sync_channel_write_len_assign_loc_tmp_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_3_U0_ap_ready <= ap_sync_read_3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_4_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_4_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_4_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_4_U0_ap_ready <= ap_sync_read_4_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_len_assign_loc_tmp1_channel <= ((ap_sync_reg_channel_write_len_assign_loc_tmp1_channel xor ap_const_logic_1) and entry_proc_U0_ap_done);
    ap_channel_done_len_assign_loc_tmp_channel <= ((ap_sync_reg_channel_write_len_assign_loc_tmp_channel xor ap_const_logic_1) and entry_proc_U0_ap_done);
    ap_done <= write_U0_ap_done;
    ap_idle <= (write_U0_ap_idle and read_4_U0_ap_idle and read_3_U0_ap_idle and projlub_U0_ap_idle and (len_assign_loc_tmp1_channel_empty_n xor ap_const_logic_1) and (len_assign_loc_tmp_channel_empty_n xor ap_const_logic_1) and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_channel_write_len_assign_loc_tmp1_channel <= ((len_assign_loc_tmp1_channel_full_n and ap_channel_done_len_assign_loc_tmp1_channel) or ap_sync_reg_channel_write_len_assign_loc_tmp1_channel);
    ap_sync_channel_write_len_assign_loc_tmp_channel <= ((len_assign_loc_tmp_channel_full_n and ap_channel_done_len_assign_loc_tmp_channel) or ap_sync_reg_channel_write_len_assign_loc_tmp_channel);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_read_3_U0_ap_ready <= (read_3_U0_ap_ready or ap_sync_reg_read_3_U0_ap_ready);
    ap_sync_read_4_U0_ap_ready <= (read_4_U0_ap_ready or ap_sync_reg_read_4_U0_ap_ready);
    ap_sync_ready <= (ap_sync_read_4_U0_ap_ready and ap_sync_read_3_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= (ap_sync_channel_write_len_assign_loc_tmp_channel and ap_sync_channel_write_len_assign_loc_tmp1_channel);
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    len_assign_loc_read <= entry_proc_U0_len_assign_loc_read;
    m_axi_gmem1_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_AWADDR <= write_U0_m_axi_gmem1_AWADDR;
    m_axi_gmem1_AWBURST <= write_U0_m_axi_gmem1_AWBURST;
    m_axi_gmem1_AWCACHE <= write_U0_m_axi_gmem1_AWCACHE;
    m_axi_gmem1_AWID <= write_U0_m_axi_gmem1_AWID;
    m_axi_gmem1_AWLEN <= write_U0_m_axi_gmem1_AWLEN;
    m_axi_gmem1_AWLOCK <= write_U0_m_axi_gmem1_AWLOCK;
    m_axi_gmem1_AWPROT <= write_U0_m_axi_gmem1_AWPROT;
    m_axi_gmem1_AWQOS <= write_U0_m_axi_gmem1_AWQOS;
    m_axi_gmem1_AWREGION <= write_U0_m_axi_gmem1_AWREGION;
    m_axi_gmem1_AWSIZE <= write_U0_m_axi_gmem1_AWSIZE;
    m_axi_gmem1_AWUSER <= write_U0_m_axi_gmem1_AWUSER;
    m_axi_gmem1_AWVALID <= write_U0_m_axi_gmem1_AWVALID;
    m_axi_gmem1_BREADY <= write_U0_m_axi_gmem1_BREADY;
    m_axi_gmem1_RREADY <= ap_const_logic_0;
    m_axi_gmem1_WDATA <= write_U0_m_axi_gmem1_WDATA;
    m_axi_gmem1_WID <= write_U0_m_axi_gmem1_WID;
    m_axi_gmem1_WLAST <= write_U0_m_axi_gmem1_WLAST;
    m_axi_gmem1_WSTRB <= write_U0_m_axi_gmem1_WSTRB;
    m_axi_gmem1_WUSER <= write_U0_m_axi_gmem1_WUSER;
    m_axi_gmem1_WVALID <= write_U0_m_axi_gmem1_WVALID;
    m_axi_gmem4_ARADDR <= read_3_U0_m_axi_gmem4_ARADDR;
    m_axi_gmem4_ARBURST <= read_3_U0_m_axi_gmem4_ARBURST;
    m_axi_gmem4_ARCACHE <= read_3_U0_m_axi_gmem4_ARCACHE;
    m_axi_gmem4_ARID <= read_3_U0_m_axi_gmem4_ARID;
    m_axi_gmem4_ARLEN <= read_3_U0_m_axi_gmem4_ARLEN;
    m_axi_gmem4_ARLOCK <= read_3_U0_m_axi_gmem4_ARLOCK;
    m_axi_gmem4_ARPROT <= read_3_U0_m_axi_gmem4_ARPROT;
    m_axi_gmem4_ARQOS <= read_3_U0_m_axi_gmem4_ARQOS;
    m_axi_gmem4_ARREGION <= read_3_U0_m_axi_gmem4_ARREGION;
    m_axi_gmem4_ARSIZE <= read_3_U0_m_axi_gmem4_ARSIZE;
    m_axi_gmem4_ARUSER <= read_3_U0_m_axi_gmem4_ARUSER;
    m_axi_gmem4_ARVALID <= read_3_U0_m_axi_gmem4_ARVALID;
    m_axi_gmem4_AWADDR <= ap_const_lv64_0;
    m_axi_gmem4_AWBURST <= ap_const_lv2_0;
    m_axi_gmem4_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem4_AWID <= ap_const_lv1_0;
    m_axi_gmem4_AWLEN <= ap_const_lv32_0;
    m_axi_gmem4_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem4_AWPROT <= ap_const_lv3_0;
    m_axi_gmem4_AWQOS <= ap_const_lv4_0;
    m_axi_gmem4_AWREGION <= ap_const_lv4_0;
    m_axi_gmem4_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem4_AWUSER <= ap_const_lv1_0;
    m_axi_gmem4_AWVALID <= ap_const_logic_0;
    m_axi_gmem4_BREADY <= ap_const_logic_0;
    m_axi_gmem4_RREADY <= read_3_U0_m_axi_gmem4_RREADY;
    m_axi_gmem4_WDATA <= ap_const_lv256_lc_1;
    m_axi_gmem4_WID <= ap_const_lv1_0;
    m_axi_gmem4_WLAST <= ap_const_logic_0;
    m_axi_gmem4_WSTRB <= ap_const_lv32_0;
    m_axi_gmem4_WUSER <= ap_const_lv1_0;
    m_axi_gmem4_WVALID <= ap_const_logic_0;
    m_axi_gmem5_ARADDR <= read_4_U0_m_axi_gmem5_ARADDR;
    m_axi_gmem5_ARBURST <= read_4_U0_m_axi_gmem5_ARBURST;
    m_axi_gmem5_ARCACHE <= read_4_U0_m_axi_gmem5_ARCACHE;
    m_axi_gmem5_ARID <= read_4_U0_m_axi_gmem5_ARID;
    m_axi_gmem5_ARLEN <= read_4_U0_m_axi_gmem5_ARLEN;
    m_axi_gmem5_ARLOCK <= read_4_U0_m_axi_gmem5_ARLOCK;
    m_axi_gmem5_ARPROT <= read_4_U0_m_axi_gmem5_ARPROT;
    m_axi_gmem5_ARQOS <= read_4_U0_m_axi_gmem5_ARQOS;
    m_axi_gmem5_ARREGION <= read_4_U0_m_axi_gmem5_ARREGION;
    m_axi_gmem5_ARSIZE <= read_4_U0_m_axi_gmem5_ARSIZE;
    m_axi_gmem5_ARUSER <= read_4_U0_m_axi_gmem5_ARUSER;
    m_axi_gmem5_ARVALID <= read_4_U0_m_axi_gmem5_ARVALID;
    m_axi_gmem5_AWADDR <= ap_const_lv64_0;
    m_axi_gmem5_AWBURST <= ap_const_lv2_0;
    m_axi_gmem5_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem5_AWID <= ap_const_lv1_0;
    m_axi_gmem5_AWLEN <= ap_const_lv32_0;
    m_axi_gmem5_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem5_AWPROT <= ap_const_lv3_0;
    m_axi_gmem5_AWQOS <= ap_const_lv4_0;
    m_axi_gmem5_AWREGION <= ap_const_lv4_0;
    m_axi_gmem5_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem5_AWUSER <= ap_const_lv1_0;
    m_axi_gmem5_AWVALID <= ap_const_logic_0;
    m_axi_gmem5_BREADY <= ap_const_logic_0;
    m_axi_gmem5_RREADY <= read_4_U0_m_axi_gmem5_RREADY;
    m_axi_gmem5_WDATA <= ap_const_lv256_lc_1;
    m_axi_gmem5_WID <= ap_const_lv1_0;
    m_axi_gmem5_WLAST <= ap_const_logic_0;
    m_axi_gmem5_WSTRB <= ap_const_lv32_0;
    m_axi_gmem5_WUSER <= ap_const_lv1_0;
    m_axi_gmem5_WVALID <= ap_const_logic_0;
    projlub_U0_ap_continue <= ap_const_logic_1;
    projlub_U0_ap_start <= start_for_projlub_U0_empty_n;
    read_3_U0_ap_continue <= ap_const_logic_1;
    read_3_U0_ap_start <= (len_assign_loc_tmp_channel_empty_n and (ap_sync_reg_read_3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_4_U0_ap_continue <= ap_const_logic_1;
    read_4_U0_ap_start <= (len_assign_loc_tmp1_channel_empty_n and (ap_sync_reg_read_4_U0_ap_ready xor ap_const_logic_1) and ap_start);
    start_for_projlub_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_write_U0_din <= (0=>ap_const_logic_1, others=>'-');
    temp_read <= projlub_U0_temp_read;
    write_U0_ap_continue <= ap_continue;
    write_U0_ap_start <= start_for_write_U0_empty_n;
end behav;
