-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pl_kernel_projlub is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    temp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    temp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    temp_empty_n : IN STD_LOGIC;
    temp_read : OUT STD_LOGIC;
    lb_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    lb_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    lb_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    lb_s_i_empty_n : IN STD_LOGIC;
    lb_s_i_read : OUT STD_LOGIC;
    ub_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    ub_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    ub_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    ub_s_i_empty_n : IN STD_LOGIC;
    ub_s_i_read : OUT STD_LOGIC;
    xupdate_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    xupdate_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    xupdate_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    xupdate_i_full_n : IN STD_LOGIC;
    xupdate_i_write : OUT STD_LOGIC;
    len_assign_loc_dout : IN STD_LOGIC_VECTOR (30 downto 0);
    len_assign_loc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    len_assign_loc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    len_assign_loc_empty_n : IN STD_LOGIC;
    len_assign_loc_read : OUT STD_LOGIC;
    len_assign_loc_c_din : OUT STD_LOGIC_VECTOR (30 downto 0);
    len_assign_loc_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    len_assign_loc_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    len_assign_loc_c_full_n : IN STD_LOGIC;
    len_assign_loc_c_write : OUT STD_LOGIC );
end;


architecture behav of pl_kernel_projlub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal len_assign_loc_blk_n : STD_LOGIC;
    signal len_assign_loc_c_blk_n : STD_LOGIC;
    signal len_reg_73 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_idle : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_ready : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_temp_read : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_lb_s_i_read : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ub_s_i_read : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_write : STD_LOGIC;
    signal grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal len_assign_loc_read_local : STD_LOGIC;
    signal len_assign_loc_c_write_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pl_kernel_projlub_Pipeline_VITIS_LOOP_42_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        temp_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        temp_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        temp_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        temp_empty_n : IN STD_LOGIC;
        temp_read : OUT STD_LOGIC;
        lb_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        lb_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        lb_s_i_empty_n : IN STD_LOGIC;
        lb_s_i_read : OUT STD_LOGIC;
        ub_s_i_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        ub_s_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        ub_s_i_empty_n : IN STD_LOGIC;
        ub_s_i_read : OUT STD_LOGIC;
        xupdate_i_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        xupdate_i_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        xupdate_i_full_n : IN STD_LOGIC;
        xupdate_i_write : OUT STD_LOGIC;
        len : IN STD_LOGIC_VECTOR (30 downto 0) );
    end component;



begin
    grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54 : component pl_kernel_projlub_Pipeline_VITIS_LOOP_42_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start,
        ap_done => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done,
        ap_idle => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_idle,
        ap_ready => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_ready,
        temp_dout => temp_dout,
        temp_num_data_valid => ap_const_lv7_0,
        temp_fifo_cap => ap_const_lv7_0,
        temp_empty_n => temp_empty_n,
        temp_read => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_temp_read,
        lb_s_i_dout => lb_s_i_dout,
        lb_s_i_num_data_valid => ap_const_lv7_0,
        lb_s_i_fifo_cap => ap_const_lv7_0,
        lb_s_i_empty_n => lb_s_i_empty_n,
        lb_s_i_read => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_lb_s_i_read,
        ub_s_i_dout => ub_s_i_dout,
        ub_s_i_num_data_valid => ap_const_lv7_0,
        ub_s_i_fifo_cap => ap_const_lv7_0,
        ub_s_i_empty_n => ub_s_i_empty_n,
        ub_s_i_read => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ub_s_i_read,
        xupdate_i_din => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_din,
        xupdate_i_num_data_valid => ap_const_lv7_0,
        xupdate_i_fifo_cap => ap_const_lv7_0,
        xupdate_i_full_n => xupdate_i_full_n,
        xupdate_i_write => grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_write,
        len => len_reg_73);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_ready = ap_const_logic_1)) then 
                    grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                len_reg_73 <= len_assign_loc_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done)
    begin
        if ((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, len_assign_loc_empty_n, len_assign_loc_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (len_assign_loc_c_full_n = ap_const_logic_0) or (len_assign_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ap_start_reg;

    lb_s_i_read_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_lb_s_i_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            lb_s_i_read <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_lb_s_i_read;
        else 
            lb_s_i_read <= ap_const_logic_0;
        end if; 
    end process;


    len_assign_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, len_assign_loc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            len_assign_loc_blk_n <= len_assign_loc_empty_n;
        else 
            len_assign_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    len_assign_loc_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, len_assign_loc_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            len_assign_loc_c_blk_n <= len_assign_loc_c_full_n;
        else 
            len_assign_loc_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    len_assign_loc_c_din <= len_assign_loc_dout;
    len_assign_loc_c_write <= len_assign_loc_c_write_local;

    len_assign_loc_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            len_assign_loc_c_write_local <= ap_const_logic_1;
        else 
            len_assign_loc_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    len_assign_loc_read <= len_assign_loc_read_local;

    len_assign_loc_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            len_assign_loc_read_local <= ap_const_logic_1;
        else 
            len_assign_loc_read_local <= ap_const_logic_0;
        end if; 
    end process;


    temp_read_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_temp_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            temp_read <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_temp_read;
        else 
            temp_read <= ap_const_logic_0;
        end if; 
    end process;


    ub_s_i_read_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ub_s_i_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ub_s_i_read <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_ub_s_i_read;
        else 
            ub_s_i_read <= ap_const_logic_0;
        end if; 
    end process;

    xupdate_i_din <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_din;

    xupdate_i_write_assign_proc : process(grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            xupdate_i_write <= grp_projlub_Pipeline_VITIS_LOOP_42_1_fu_54_xupdate_i_write;
        else 
            xupdate_i_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
