// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Infeasi_Res_S2_loadDDR_data_22 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY,
        m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY,
        m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST,
        m_axi_gmem4_WID,
        m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST,
        m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID,
        m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP,
        m_axi_gmem4_BID,
        m_axi_gmem4_BUSER,
        mem,
        colScale_fifo_din,
        colScale_fifo_num_data_valid,
        colScale_fifo_fifo_cap,
        colScale_fifo_full_n,
        colScale_fifo_write,
        len,
        n_c1_din,
        n_c1_num_data_valid,
        n_c1_fifo_cap,
        n_c1_full_n,
        n_c1_write
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem4_AWVALID;
input   m_axi_gmem4_AWREADY;
output  [63:0] m_axi_gmem4_AWADDR;
output  [0:0] m_axi_gmem4_AWID;
output  [31:0] m_axi_gmem4_AWLEN;
output  [2:0] m_axi_gmem4_AWSIZE;
output  [1:0] m_axi_gmem4_AWBURST;
output  [1:0] m_axi_gmem4_AWLOCK;
output  [3:0] m_axi_gmem4_AWCACHE;
output  [2:0] m_axi_gmem4_AWPROT;
output  [3:0] m_axi_gmem4_AWQOS;
output  [3:0] m_axi_gmem4_AWREGION;
output  [0:0] m_axi_gmem4_AWUSER;
output   m_axi_gmem4_WVALID;
input   m_axi_gmem4_WREADY;
output  [511:0] m_axi_gmem4_WDATA;
output  [63:0] m_axi_gmem4_WSTRB;
output   m_axi_gmem4_WLAST;
output  [0:0] m_axi_gmem4_WID;
output  [0:0] m_axi_gmem4_WUSER;
output   m_axi_gmem4_ARVALID;
input   m_axi_gmem4_ARREADY;
output  [63:0] m_axi_gmem4_ARADDR;
output  [0:0] m_axi_gmem4_ARID;
output  [31:0] m_axi_gmem4_ARLEN;
output  [2:0] m_axi_gmem4_ARSIZE;
output  [1:0] m_axi_gmem4_ARBURST;
output  [1:0] m_axi_gmem4_ARLOCK;
output  [3:0] m_axi_gmem4_ARCACHE;
output  [2:0] m_axi_gmem4_ARPROT;
output  [3:0] m_axi_gmem4_ARQOS;
output  [3:0] m_axi_gmem4_ARREGION;
output  [0:0] m_axi_gmem4_ARUSER;
input   m_axi_gmem4_RVALID;
output   m_axi_gmem4_RREADY;
input  [511:0] m_axi_gmem4_RDATA;
input   m_axi_gmem4_RLAST;
input  [0:0] m_axi_gmem4_RID;
input  [12:0] m_axi_gmem4_RFIFONUM;
input  [0:0] m_axi_gmem4_RUSER;
input  [1:0] m_axi_gmem4_RRESP;
input   m_axi_gmem4_BVALID;
output   m_axi_gmem4_BREADY;
input  [1:0] m_axi_gmem4_BRESP;
input  [0:0] m_axi_gmem4_BID;
input  [0:0] m_axi_gmem4_BUSER;
input  [63:0] mem;
output  [511:0] colScale_fifo_din;
input  [2:0] colScale_fifo_num_data_valid;
input  [2:0] colScale_fifo_fifo_cap;
input   colScale_fifo_full_n;
output   colScale_fifo_write;
input  [31:0] len;
output  [31:0] n_c1_din;
input  [2:0] n_c1_num_data_valid;
input  [2:0] n_c1_fifo_cap;
input   n_c1_full_n;
output   n_c1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem4_ARVALID;
reg[63:0] m_axi_gmem4_ARADDR;
reg[0:0] m_axi_gmem4_ARID;
reg[31:0] m_axi_gmem4_ARLEN;
reg[2:0] m_axi_gmem4_ARSIZE;
reg[1:0] m_axi_gmem4_ARBURST;
reg[1:0] m_axi_gmem4_ARLOCK;
reg[3:0] m_axi_gmem4_ARCACHE;
reg[2:0] m_axi_gmem4_ARPROT;
reg[3:0] m_axi_gmem4_ARQOS;
reg[3:0] m_axi_gmem4_ARREGION;
reg[0:0] m_axi_gmem4_ARUSER;
reg m_axi_gmem4_RREADY;
reg colScale_fifo_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem4_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    n_c1_blk_n;
reg    ap_block_state1;
wire   [30:0] empty_fu_110_p3;
reg   [30:0] empty_reg_148;
wire  signed [57:0] trunc_ln_fu_118_p4;
reg   [57:0] trunc_ln_reg_153;
wire   [63:0] zext_ln58_fu_139_p1;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_idle;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_ready;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWVALID;
wire   [63:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWADDR;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWID;
wire   [31:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWLEN;
wire   [2:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWSIZE;
wire   [1:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWBURST;
wire   [1:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWLOCK;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWCACHE;
wire   [2:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWPROT;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWQOS;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWREGION;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWUSER;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WVALID;
wire   [511:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WDATA;
wire   [63:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WSTRB;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WLAST;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WID;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WUSER;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARVALID;
wire   [63:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARADDR;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARID;
wire   [31:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLEN;
wire   [2:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARSIZE;
wire   [1:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARBURST;
wire   [1:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLOCK;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARCACHE;
wire   [2:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARPROT;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARQOS;
wire   [3:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARREGION;
wire   [0:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARUSER;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_RREADY;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_BREADY;
wire   [511:0] grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_din;
wire    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_write;
reg    grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire  signed [63:0] sext_ln58_fu_128_p1;
reg    n_c1_write_local;
wire   [0:0] icmp_ln58_fu_100_p2;
wire   [30:0] trunc_ln58_fu_106_p1;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 14'd1;
#0 grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg = 1'b0;
end

Infeasi_Res_S2_loadDDR_data_22_Pipeline_loadDDR_data grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start),
    .ap_done(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done),
    .ap_idle(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_idle),
    .ap_ready(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_ready),
    .m_axi_gmem4_AWVALID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWVALID),
    .m_axi_gmem4_AWREADY(1'b0),
    .m_axi_gmem4_AWADDR(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWADDR),
    .m_axi_gmem4_AWID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWID),
    .m_axi_gmem4_AWLEN(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWLEN),
    .m_axi_gmem4_AWSIZE(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWSIZE),
    .m_axi_gmem4_AWBURST(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWBURST),
    .m_axi_gmem4_AWLOCK(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWLOCK),
    .m_axi_gmem4_AWCACHE(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWCACHE),
    .m_axi_gmem4_AWPROT(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWPROT),
    .m_axi_gmem4_AWQOS(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWQOS),
    .m_axi_gmem4_AWREGION(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWREGION),
    .m_axi_gmem4_AWUSER(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_AWUSER),
    .m_axi_gmem4_WVALID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WVALID),
    .m_axi_gmem4_WREADY(1'b0),
    .m_axi_gmem4_WDATA(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WDATA),
    .m_axi_gmem4_WSTRB(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WSTRB),
    .m_axi_gmem4_WLAST(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WLAST),
    .m_axi_gmem4_WID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WID),
    .m_axi_gmem4_WUSER(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_WUSER),
    .m_axi_gmem4_ARVALID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARVALID),
    .m_axi_gmem4_ARREADY(m_axi_gmem4_ARREADY),
    .m_axi_gmem4_ARADDR(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARADDR),
    .m_axi_gmem4_ARID(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARID),
    .m_axi_gmem4_ARLEN(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLEN),
    .m_axi_gmem4_ARSIZE(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARSIZE),
    .m_axi_gmem4_ARBURST(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARBURST),
    .m_axi_gmem4_ARLOCK(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLOCK),
    .m_axi_gmem4_ARCACHE(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARCACHE),
    .m_axi_gmem4_ARPROT(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARPROT),
    .m_axi_gmem4_ARQOS(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARQOS),
    .m_axi_gmem4_ARREGION(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARREGION),
    .m_axi_gmem4_ARUSER(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARUSER),
    .m_axi_gmem4_RVALID(m_axi_gmem4_RVALID),
    .m_axi_gmem4_RREADY(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_RREADY),
    .m_axi_gmem4_RDATA(m_axi_gmem4_RDATA),
    .m_axi_gmem4_RLAST(m_axi_gmem4_RLAST),
    .m_axi_gmem4_RID(m_axi_gmem4_RID),
    .m_axi_gmem4_RFIFONUM(m_axi_gmem4_RFIFONUM),
    .m_axi_gmem4_RUSER(m_axi_gmem4_RUSER),
    .m_axi_gmem4_RRESP(m_axi_gmem4_RRESP),
    .m_axi_gmem4_BVALID(1'b0),
    .m_axi_gmem4_BREADY(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_BREADY),
    .m_axi_gmem4_BRESP(2'd0),
    .m_axi_gmem4_BID(1'd0),
    .m_axi_gmem4_BUSER(1'd0),
    .colScale_fifo_din(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_din),
    .colScale_fifo_num_data_valid(3'd0),
    .colScale_fifo_fifo_cap(3'd0),
    .colScale_fifo_full_n(colScale_fifo_full_n),
    .colScale_fifo_write(grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_write),
    .len(len),
    .sext_ln58(trunc_ln_reg_153)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_ready == 1'b1)) begin
            grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_148 <= empty_fu_110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_gmem4_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln_reg_153 <= {{mem[63:6]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem4_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        colScale_fifo_write = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_write;
    end else begin
        colScale_fifo_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem4_blk_n_AR = m_axi_gmem4_ARREADY;
    end else begin
        gmem4_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem4_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_ARADDR = sext_ln58_fu_128_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARADDR = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARADDR;
    end else begin
        m_axi_gmem4_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARBURST = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARBURST;
    end else begin
        m_axi_gmem4_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARCACHE = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARCACHE;
    end else begin
        m_axi_gmem4_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARID = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARID;
    end else begin
        m_axi_gmem4_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem4_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_ARLEN = zext_ln58_fu_139_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARLEN = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLEN;
    end else begin
        m_axi_gmem4_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARLOCK = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARLOCK;
    end else begin
        m_axi_gmem4_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARPROT = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARPROT;
    end else begin
        m_axi_gmem4_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARQOS = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARQOS;
    end else begin
        m_axi_gmem4_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARREGION = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARREGION;
    end else begin
        m_axi_gmem4_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARSIZE = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARSIZE;
    end else begin
        m_axi_gmem4_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARUSER = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARUSER;
    end else begin
        m_axi_gmem4_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem4_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_ARVALID = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_ARVALID;
    end else begin
        m_axi_gmem4_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem4_RREADY = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_m_axi_gmem4_RREADY;
    end else begin
        m_axi_gmem4_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_c1_blk_n = n_c1_full_n;
    end else begin
        n_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        n_c1_write_local = 1'b1;
    end else begin
        n_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem4_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (n_c1_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign colScale_fifo_din = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_colScale_fifo_din;

assign empty_fu_110_p3 = ((icmp_ln58_fu_100_p2[0:0] == 1'b1) ? trunc_ln58_fu_106_p1 : 31'd0);

assign grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start = grp_loadDDR_data_22_Pipeline_loadDDR_data_fu_84_ap_start_reg;

assign icmp_ln58_fu_100_p2 = (($signed(len) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem4_AWADDR = 64'd0;

assign m_axi_gmem4_AWBURST = 2'd0;

assign m_axi_gmem4_AWCACHE = 4'd0;

assign m_axi_gmem4_AWID = 1'd0;

assign m_axi_gmem4_AWLEN = 32'd0;

assign m_axi_gmem4_AWLOCK = 2'd0;

assign m_axi_gmem4_AWPROT = 3'd0;

assign m_axi_gmem4_AWQOS = 4'd0;

assign m_axi_gmem4_AWREGION = 4'd0;

assign m_axi_gmem4_AWSIZE = 3'd0;

assign m_axi_gmem4_AWUSER = 1'd0;

assign m_axi_gmem4_AWVALID = 1'b0;

assign m_axi_gmem4_BREADY = 1'b0;

assign m_axi_gmem4_WDATA = 512'd0;

assign m_axi_gmem4_WID = 1'd0;

assign m_axi_gmem4_WLAST = 1'b0;

assign m_axi_gmem4_WSTRB = 64'd0;

assign m_axi_gmem4_WUSER = 1'd0;

assign m_axi_gmem4_WVALID = 1'b0;

assign n_c1_din = len;

assign n_c1_write = n_c1_write_local;

assign sext_ln58_fu_128_p1 = trunc_ln_fu_118_p4;

assign start_out = real_start;

assign trunc_ln58_fu_106_p1 = len[30:0];

assign trunc_ln_fu_118_p4 = {{mem[63:6]}};

assign zext_ln58_fu_139_p1 = empty_reg_148;

endmodule //Infeasi_Res_S2_loadDDR_data_22
